### ISSUE TITLE
Wyze Video DoorBell and Video DoorBell Pro Support

### ISSUE THREAD

**Issue by yodaluca23** [jfarmer08/homebridge-wyze-smart-home#100]
**Is your feature request related to a problem? Please describe:**
I want to be able to view my doorbell from my AppleTV.

**Describe the solution you'd like:**
Support for viewing the camera feed from the doorbell, and snapshot history, and have it formatted as a doorbell.

**Describe alternatives you've considered:**
Just having it show up as a normal camera...

**Comment by anderfrank** [comment]
Docker-Wyze-Bridge supports the doorbell (non-pro model). You'll also need something like Scrypted (or Camera.UI in Homebridge) to get it into HomeKit.

I'm not aware of any current Homebridge plugins that support viewing cameras.

**Comment by yodaluca23** [comment]
> I'm not aware of any current Homebridge plugins that support viewing cameras.

Their are ones for Nest Cameras.

**Comment by anderfrank** [comment]
Sorry should have clarified, I was referring to other Wyze plugins.

**Comment by jfarmer08** [comment]
This is not in the current plan. There are ways to do this using Docker-Wyze-Bridge and Homebridge-Camera-UI

**Comment by holocronology** [comment]
> Docker-Wyze-Bridge

Doesn't work with Doorbell Pro and other new cameras (OG, Telephoto, etc...)

**Comment by carTloyal123** [comment]
Please see this thread for more info, otherwise this is closed for now and can be tracked using the wyze-api issue or the Cryze repo for video related items

[Video Doorbell Support](https://github.com/jfarmer08/homebridge-wyze-smart-home/issues/182#issuecomment-1942133497)
