### ISSUE TITLE
Support for BR30 Mesh Color Bulb

### ISSUE THREAD

**Issue by flarghon** [jfarmer08/homebridge-wyze-smart-home#101]
**Is your feature request related to a problem? Please describe:**
When I add a BR30 Wyze Color Bulb to my homebridge it continually crashes my wyze child bridge

**Comment by jfarmer08** [comment]
I can only add hardware that I own. With that said I will see what I can do.

**Comment by jfarmer08** [comment]
@flarghon If your still using the plugin maybe you can turn on debug logging and send that to me. I will see why it crashing.

**Comment by jfarmer08** [comment]
I have a separate account from my main. So maybe sharing that device with me would allow me to see what info is in the payloads.

Wyzeapi@gmail.com
