### ISSUE TITLE
Garage Door Opener with Wyze to have Garage Door Open Switch

### ISSUE THREAD

**Issue by Spatulamb** [jfarmer08/homebridge-wyze-smart-home#107]
**Is your feature request related to a problem? Please describe:**
With this plugin, I am able to see the garage cam from Wyze but I am only able to turn it on or off, not control the garage door that the cam is paired with.

**Describe the solution you'd like:**
Would like there be a switch for garage door cam so that can be activated or deactivated by clicking

**Describe alternatives you've considered:**
Because the cam recognizes if the door is closed or open, if there's way to represent that information via different thing, i.e. have it as door and show status, that would be even better but not sure if that's possible under Apple Home

Thank you very much for making this plugin!

**Comment by jfarmer08** [comment]
I can only add hardware that I own. With that said I will see what I can do.

**Comment by evilgenius31** [comment]
Would a packet capture of the traffic when opening/closing the garage door help at all?

**Comment by jfarmer08** [comment]
I cannot say it wouldn’t. Any would help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jfarmer08** [comment]
I have a separate account from my main. So maybe sharing that device with me would allow me to see what info is in the payloads. 

Wyzeapi@gmail.com

**Comment by andrewgai** [comment]
Would love to be able to control the garage as well, I just shared the device with your account. I'm hoping to be able to control this with Siri via homebridge so I can stop having to open the amazon app on my phone and provide a pin to operate the garage every time :)

**Comment by jfarmer08** [comment]
@andrewgai Let me see what I can find out. Hopefully it's similar to the Siren or Light. I will have to press the button at some point, but I will make sure you are around before I do something like that.

**Comment by andrewgai** [comment]
Go for it, let me know :)

**Comment by KodySalak** [comment]
@jfarmer08 I can also provide any help needed. Just installed this and realized _after_ I bought it that it won't open the door on a schedule/arrival and I find that irritating :)

**Comment by jfarmer08** [comment]
If anyone can share with me the garage door please do. I would like to test a some code to see if it's working. 

wyzeapi@gmail.com

**Comment by KodySalak** [comment]
Shared with you. Please don't shut it for too long - garage is very warm!

**Comment by jfarmer08** [comment]
Thank you. I have looked at my code and it's still not right, you can remove access for now or leave it. I will not have time to work on this until tomorrow morning. 


Thanks again

**Comment by DiscoveryOV** [comment]
@jfarmer08 I plan on getting one of these soon, anything I can do to help speed development once I do get one?

Also, thank you for all your hard work! I love Wyze and native HomeKit support is the only thing "missing" from their products (well, that and background audio for the cameras).

**Comment by jfarmer08** [comment]
Can someone share their garage door with me? [wyzeapi@gmail.com](mailto:wyzeapi@gmail.com)

**Comment by jfarmer08** [comment]
Thank you @KodySalak. We have support for the garage door in the API, now we just need to update the plugin. Soon as i can get to it I will.

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.1

**Comment by jfarmer08** [comment]
@KodySalak if you have time to download this release let me know. I am not sure I have it 100%

**Comment by KodySalak** [comment]
Testing as we speak - will let you know the outcome.

**Comment by KodySalak** [comment]
Nice work!

Initial "adding" to the home: It did some weird things when I initially added it (Garage was _closed_ and Wyze detected it as closed). It was stuck on the status of "Opening..." and once I tapped it to "closed", it instantly went to closed on the home app and the garage door started opening.

After the opening of the garage door, the app showed "open" and it was correct. I closed it and it closed as expected. I left the home app to check something and when I got back to it, it says "opening..." again. 

hombridge.log (debug mode) is heading your way via email.

**Comment by jfarmer08** [comment]
Ok I will take a look at this. Thank you for the logs.

**Comment by jfarmer08** [comment]
@KodySalak I need someone to share the garage door with me again. So that I can capture the state changes.

**Comment by KodySalak** [comment]
I’ll have to have you wait until at least Tuesday, apologies for the delay. If anyone else in this thread can step in, that would be best.

**Comment by jfarmer08** [comment]
@KodySalak @andrewgai @evilgenius31 @DiscoveryOV 

If anyone can share the garage door, I should have time to look at it today.

**Comment by jfarmer08** [comment]
@KodySalak I am finished for now. There is room for improvements, but sometime later or someone else can help with it. I will upload a new release soon.
