### ISSUE TITLE
Thermostat temperature does not get set

### ISSUE THREAD

**Issue by xenonaxel** [jfarmer08/homebridge-wyze-smart-home#111]
Followed documentation to setup plugin in Homebridge. When I go to set the temperature for the Wyze thermostat it does not get set on the device itself. I reload the home app and my change gets reverted. I am able to change the state just not the temperature

I have installed different versions and tried to modify the code with my limited knowledge. It has always been reproduceable on my instance

When I set the temperature in the Home app the device will reflect the change

There is nothing in the logs as far as I can tell.

        {
            "name": "Wyze",
            "username": "email@domain.com",
            "password": "password",
            "refreshInterval": 60000,
            "entryExitDelay": 30,
            "mfaCode": "502640",
            "showAdvancedOptions": true,
            "excludeMacAddress": false,
            "excludedeviceType": true,
            "filterDeviceTypeList": [
                "Camera"
            ],
            "platform": "WyzeSmartHome"
        }

**Plugin Version**: 0.5.28
**Homebridge Version**: v1.6.1
**Node.js Version**: v18.16.0
**NPM Version**: 9.5.1
**Operating System**: Debian 10

**Comment by jfarmer08** [comment]
@carTloyal123 Have you seen anything like this with the Thermostat?

**Comment by xenonaxel** [comment]
@jfarmer08 Any I can grab from my end to help?

**Comment by jfarmer08** [comment]
Can you turn on debug and send me the full log?

**Comment by carTloyal123** [comment]
I have not seen this be an issue before as far as I remember. Some logs would be great! I suppose it’s possible something has changed recently on theWyze side but I haven’t seen any device updates to suggest that.

**Comment by xenonaxel** [comment]
I turned debug on and got the logs. You can see around line 60 I set the temperature in the home app. I closed it and reopened it and it reverted to the original status.
[homebridge.log.txt](https://github.com/jfarmer08/homebridge-wyze-smart-home/files/11995363/homebridge.log.txt)

**Comment by xenonaxel** [comment]
More weird behavior. When I change it in the Home app it just immediately reverts the change now.
`[7/9/2023, 9:55:11 AM] [Wyze] [Thermostat] Getting targetTemperature status of "Wyze Thermostat" to 75
[7/9/2023, 9:55:11 AM] [Wyze] Thermostat Target Temp: 76
[7/9/2023, 9:55:11 AM] [Wyze] Thermostat Cool Setpoint: 76
[7/9/2023, 9:55:11 AM] [Wyze] Thermostat Heat Setpoint: 68`

**Comment by jfarmer08** [comment]
@xenonaxel  So it is working or its not working?

**Comment by xenonaxel** [comment]
@jfarmer08 it is not working. The temperature still resets. It seems to switch between not ever taking the change or saying it changed but after I reopen the app it doesn't. as @carTloyal123 mentioned I don't think it's been set in the plugin. From my understanding of the logs it just queries the device again to get the current temperature instead of updating it.

Another thing I noticed in the logs is it keeps saying pulling cached device for the wyze thermostat but does not happen for any other device

**Comment by carTloyal123** [comment]
And what about other automations and the mode you are trying to use for your system? @xenonaxel

**Comment by xenonaxel** [comment]
@carTloyal123 Sorry forgot to add that to the reply. I am not using anything in addition to homebridge to automate my Wyze Thermostat. It doesn't seem to matter the mode. AC, Heat or Auto the temperature will not change. I can change the mode  in HomeKit and it changes on the device. So part of it works just not setting the temp.

**Comment by carTloyal123** [comment]
Gotcha thank you. As far as I can tell, the auto mode should work just fine. To be clear, this is the mode in HomeKit where you can set both the high and low temp on the same screen. This is the mode I built the plugin specifically for since all three modes (heat, cool and auto) are implemented separately. Do me a favor and set the system to auto, wait until a new set of log messages come up with the thermostat status, then set the heat or cool temp. If you will post that log for me that would be fantastic. Pretty much all of my testing and debugging revolved around auto mode so let’s nail that down first, thanks!

**Comment by xenonaxel** [comment]
[homebridge.log (1).txt](https://github.com/jfarmer08/homebridge-wyze-smart-home/files/12003475/homebridge.log.1.txt)
Sure thing. Logs attached. Also I apologize. Auto mode does work. It changes on the device.

**Comment by xenonaxel** [comment]
@carTloyal123 
[homebridge.log (2).txt](https://github.com/jfarmer08/homebridge-wyze-smart-home/files/12004154/homebridge.log.2.txt)
Additional logs. I set it back to cool after setting the auto temp.

**Comment by carTloyal123** [comment]
Thank you for the extra logs, that will be helpful. So to confirm, your system on AUTO mode works totally correctly OR it only sets the system to auto but changing the temperature is still broken once in AUTO mode?

**Comment by carTloyal123** [comment]
@xenonaxel awesome thanks for confirming that. I will check this out this week and maybe even today if I have time later. @jfarmer08 you can assign it to me if you like and I’ll follow up with updates

**Comment by jfarmer08** [comment]
@carTloyal123 Any Update on this?

**Comment by carTloyal123** [comment]
I have a fix I think. Haven’t been home this week to test it but I will today.

**Comment by carTloyal123** [comment]
So, I have an update on my own fork of the repo and I will submit a PR to finalize it. As far as I can tell, the behavior should be more appropriate now for heat/cool single modes. I would definitely like for @xenonaxel to test it on his system so we can confirm everyone has the same experience. My device is currently not being used in my home  but I have been testing as best I can. I will link the PR here shortly

**Comment by carTloyal123** [comment]
#119

**Comment by xenonaxel** [comment]
@carTloyal123 Looks to be working! The only oddity I noticed is if I switch from cool to heat or vice versa the temperature doesn't update until I reopen the app but that's more user experience. It doesn't break functionality. Thank you so much for your work on this.

**Comment by carTloyal123** [comment]
Great to hear it is behaving better now. If you want to demonstrate the issue of changing from heat to cool or vice versa and send a log and/or a screen capture of your iOS device that would be great. Now that I have my development environment set back up it is much easier to make updates.

**Comment by carTloyal123** [comment]
Also, it looks like @jfarmer08 has not merged my changes yet so did you get a version of the plugin from my development PR? How did you get the new version to test? @xenonaxel

**Comment by carTloyal123** [comment]
@xenonaxel what exactly do you mean the temp doesn't update until you restart the app? What are you expecting to happen? Could you give me an example here?

**Comment by xenonaxel** [comment]
@carTloyal123 Yes, I took it from your development PR. I will test more thoroughly when @jfarmer08 updates the main repo.
I have screenshots of the behavior. 

<img width="163" alt="Screenshot 2023-07-16 at 3 03 16 PM" src="https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/13933997/ebdb7bfc-24c7-4b71-ad2f-b6d6f174d6bd">
Reflects current state and temperature.
<img width="164" alt="Screenshot 2023-07-16 at 3 03 25 PM" src="https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/13933
I switch it to heat mode. It says heat to 74. (Which is the temperature from the cooling state)
<img width="164" alt="Screenshot 2023-07-16 at 3 03 31 PM" src="https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/13933997/c24466be-afc0-4d97-bfaa-15dfc4417eb4">
I close the Home App and reopen it. It shows the correct temperature. 

From what I can tell this is just a UI bug. My guess is when I switch states it's not calling for the new temperature data right away until I relaunch the app.

**Comment by carTloyal123** [comment]
@xenonaxel awesome thanks for the extra info. I can also recreate this on my test setup. I think I can fix this but you are right that the current Homekit implementation does not actually ask for the  corresponding temperature when changing modes. Not sure if  this is on  purpose from Apple or  if the expectation is that the accessory should handle this. Either way I am working on  a fix and will update if it looks good. Thanks for the extra info!

**Comment by carTloyal123** [comment]
I pushed a small change that is a bit of a hack until I can find out what the correct behavior/data flow should be.

**Comment by carTloyal123** [comment]
@jfarmer08 thanks  for the merge, would you close this issue please?

**Comment by Barba4life** [comment]
how would one go about applying your fix?

**Comment by carTloyal123** [comment]
If you have the last est version of the plugin it should be applied already. Feel free to open a new issue if you are still seeing strange behavior
