### ISSUE TITLE
Issues when HMS does not have a support plan and is not excluded

### ISSUE THREAD

**Issue by jfarmer08** [jfarmer08/homebridge-wyze-smart-home#115]
Issues when HMS does not have a support plan

**Comment by jfarmer08** [comment]
@vascott1

So you're not able to see your Leak Sensor in HomeKit is that correct? Can you enable debug and then send me the logs?

**Comment by vascott1** [comment]
Seems they are there. I am not sure when they showed up but they are. I am using 0.5.30 so I think I am settled. If you want me to try at some point with the MAC address exclusion just let me know.
  
  
  
  
  
  
  

  
  
>

**Comment by jfarmer08** [comment]
So that's what should happen. So in the future I will automatically exclude the HMS Bridge and so for the ones that have it will have to include it in the config. Unless i can find the time to exclude it based on the code.

**Comment by jfarmer08** [comment]
Also, future reference, the HMS bridge is known as “S1Gateway” in the config.

**Comment by vascott1** [comment]
Oh. Ok. Good to know. I will switch from my   Mac exclude    to that.
  
  
  
  
  
  
  

  
  
>

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.3

I will update the readme to reflect the changes
