### ISSUE TITLE
Common (Model: BS_WK1) not supported

### ISSUE THREAD

**Issue by bunnyc1986** [jfarmer08/homebridge-wyze-smart-home#125]
**Describe Your Problem:**

After upgraded to v0.5.34, I started seeing `Common (Model: BS_WK1) not supported` errors in logs

**Logs:**

<img width="1053" alt="image" src="https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/1644274/342151e8-3370-48fb-a106-7a937719cfd4">

**Plugin Config:**

```json
{
    "name": "Wyze",
    "username": "***",
    "password": "***",
    "mfaCode": "***",
    "keyId": "***",
    "apiKey": "***",
    "refreshInterval": 60000,
    "entryExitDelay": 30,
    "showAdvancedOptions": false,
    "logging": "none",
    "excludeMacAddress": false,
    "excludedeviceType": false,
    "_bridge": {
        "username": "***",
        "port": ***
    },
    "platform": "WyzeSmartHome"
}
```

**Screenshots:**
See above

**Environment:**

* **Plugin Version**: v0.5.34
* **Homebridge Version**: v1.6.1
* **Node.js Version**: v18.13.0
* **NPM Version**: 8.19.3
* **Operating System**: Ubuntu Focal Fossa (20.04.5 LTS)

**Comment by jfarmer08** [comment]
Do you know what Common (Model: BS_WK1) is? What kind of device?

**Comment by jfarmer08** [comment]
All this means is that it's not in the supported list. It should still show in HomeKit and if everything works as expected please add a request to have it added.

**Comment by jfarmer08** [comment]
When submitting a request I will need the type/model and description

**Comment by ourstanley** [comment]
I think this could be the base station that is used along with the Outdoor Cam. Do the other folks seeing this have one of those as well? Or maybe it’s the bridge which works with the 1st generation of sensors - I have a couple of contact sensors and a motion sensor which are detected by the plugin, but don’t see the bridge that plugs into the back of one of my v1 cameras.

**Comment by bunnyc1986** [comment]
I don't know which device it is. I don't see this error before upgrading to the new version, neither I had new wyze device.

**Comment by bunnyc1986** [comment]
> I think this could be the base station that is used along with the Outdoor Cam. Do the other folks seeing this have one of those as well? Or maybe it’s the bridge which works with the 1st generation of sensors - I have a couple of contact sensors and a motion sensor which are detected by the plugin, but don’t see the bridge that plugs into the back of one of my v1 cameras.

I don't have the Outdoor Cam.
I do have a home security hub.
How could I find it out? Is there a way to print out its MAC address?

**Comment by jfarmer08** [comment]
@bunnyc1986 yes I can add something to print out the MAC address

**Comment by efloyd** [comment]
The same is happening for me for both of my Wyze Cam Outdoor V2 cameras. Alexa routines allow only "human presence detection" for the Wyze Outdoor Cam, so I was hoping this plugin would expose a general motion sensor that I could use as a trigger.

**Comment by jfarmer08** [comment]
@mrlt8  How are you pulling Motion Sensor Data in your Docker Bridge?

**Comment by jfarmer08** [comment]
[v0.5.36](https://github.com/jfarmer08/homebridge-wyze-smart-home/commit/34bf682424ea1a29d821bf4a3ce327a4d38ce78d)

**Comment by bunnyc1986** [comment]
thanks for adding the log. It's the Sprinkler. It probably can be excluded.

**Comment by jfarmer08** [comment]
I will exclude it in the next release.

**Comment by MTWiley** [comment]
I'm seeing this as well and it's definitely the sprinkler.

Would be great if there's a way to add support for them, but I totally understand if that's not currently a priority/possible.

**Comment by carTloyal123** [comment]
> @mrlt8  How are you pulling Motion Sensor Data in your Docker Bridge?

Are you talking about camera motion detections? Or a real motion sensor?

**Comment by jfarmer08** [comment]
I am talking about camera motion detection.

**Comment by carTloyal123** [comment]
I think you can query events from a timeframe but I don't think docker-wyze-bridge does this. Where does this show up in docker-wyze-bridge? Most questions here are directed to using the scrypted platform to do motion detection locally for homekit

**Comment by Irishsmash** [comment]
I'm getting the same issue (and I have 'common' devices excluded. The "BS_WK1" item is the Sprinkler. I have it excluded both by MAC and device type and I still get the same log error every minute...

![image](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/43126981/1508ed07-ffc9-49e3-86c0-261fcc06e922)

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.4
