### ISSUE TITLE
Forbidden / 403 Errors

### ISSUE THREAD

**Issue by alardierejr** [jfarmer08/homebridge-wyze-smart-home#127]
**Describe Your Problem:**
Starting today the plugin stopped working. I reinstalled, restarted, checked password and it still will not work now. No 2 factor turned on

**Logs:**

BridgeWARNINGunhandled rejection: Error: ENOENT: no such file or directory, open '/var/lib/hoobs/wyzesmarthomebridge/persist/wyze-51298708-78cf-4d01-8ccb-9d057574d999.json'
7/21/2023, 10:53:42 PMWyze Smart Home BridgeWyzeERRORRequest failed: Error: Request failed with status code 403
7/21/2023, 10:53:42 PMWyze Smart Home BridgeWyzeERRORResponse (Forbidden): ""
7/21/2023, 10:53:42 PMWyze Smart Home BridgeWyzeERRORError getting devices: Error: Request failed with status code 403
7/21/2023, 10:54:43 PMWyze Smart Home BridgeWyzeERRORRequest failed: Error: Request failed with status code 403
7/21/2023, 10:54:43 PMWyze Smart Home BridgeWyzeERRORResponse (Forbidden): ""
7/21/2023, 10:54:43 PMWyze Smart Home BridgeWyzeERRORError getting devices: Error: Request failed with status code 403

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **0.5.3;**:
* **4.3.0**: 
* **Node.js Version**: 
* **NPM Version**: 
* **HOOBS**:

**Comment by mrlt8** [comment]
You need to add a keyId and apiKey. 

See: https://github.com/jfarmer08/homebridge-wyze-smart-home#optional-fields

**Comment by tryphoon** [comment]
That's a tricky one to find. Not documented in the UI. Also, will need a refresh after 12 months as I'll never remember that I need to check this site to refresh my tokens and copy them in there.

**Comment by mrlt8** [comment]
The API key was still optional when the feature was merged earlier this month.

@jfarmer08 may want to make the key and ID a hard requirement now that it's required?

**Comment by jfarmer08** [comment]
[v0.5.36](https://github.com/jfarmer08/homebridge-wyze-smart-home/commit/34bf682424ea1a29d821bf4a3ce327a4d38ce78d)

**Comment by BarnesGH** [comment]
I’m also having the same issue. I put the API and Key ID in but same message on the logs and no devices pull in. 
I was struggling with getting it to let me view the entire API key. I suppose it could be that that was incorrect, so I am looking at that now.

**Comment by BarnesGH** [comment]
I got my API Key and Key ID put in correctly. Now, this is the error I see in the log:

Wyze Smart Home Bridge2WARNINGunhandled rejection: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

**Comment by rt1711** [comment]
Cant figure out what im doing wrong here.  I added everything into my plugin and generated the api key and keyid but am still getting errors.  I’m getting illegal argument undefined now instead of the 403 error.   Any ideas what I am missing?

**Comment by jfarmer08** [comment]
Can you paste your config?

**Comment by rt1711** [comment]
I had the MFA line in at one point but I disabled it and removed the line for troubleshooting.  This is what I currently have.  Thanks.

{
    "platform": "WyzeSmartHome",
    "name": "Wyze",
    "username": "email@emailhere.fake",
    "password": "fasfasifjasifja",
    "refreshInterval": 60000,
    "keyId": "abcdefg-hijk-lmnop-qrst-uvwxwz",
    "apiKey": "oajfoasjfosajfoasjfoasjfoasjfopsajfa"
}

**Comment by jfarmer08** [comment]
That looks fine - Can you add "logging": "debug" to the config and restart.

**Comment by rt1711** [comment]
Started working after adding that. No clue why
