### ISSUE TITLE
GW_GC1 Support

### ISSUE THREAD

**Issue by dallasjanssen** [jfarmer08/homebridge-wyze-smart-home#129]
I would like to see support for the camera model GW_GC1! This is the Wyze Cam OG which was released last year or this year. My homebridge is repeatedly notifying me that it is not supported despite attempting to exclude it. 

Log shows: PM] [Wyze] Camera (Mo del: GW_GC1 (Mac:xxxxxxx (Name: Garage OG) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found

**Comment by jfarmer08** [comment]
[v0.5.36](https://github.com/jfarmer08/homebridge-wyze-smart-home/commit/34bf682424ea1a29d821bf4a3ce327a4d38ce78d)

**Comment by dallasjanssen** [comment]
Hello, I am on v0.5.36 and am still seeing this message in my log.

**Comment by jfarmer08** [comment]
Does the camera work as expected in your system. Can you use the switch to turn it on and off?

**Comment by kzaleski** [comment]
I'm on v0.5.36 and seeing the same in my log files.  I can see the switch to turn on/off, but was hoping to be able to see the video.

**Comment by dallasjanssen** [comment]
yes,  it does work to turn on and off as expected.

**Comment by kzaleski** [comment]
My bad, just re-read and see the support for cameras allows on/off, not video.
