### ISSUE TITLE
Nothing Works

### ISSUE THREAD

**Issue by sisuwest** [jfarmer08/homebridge-wyze-smart-home#130]
This plugin used to work until last week. Now none of my accessories respond in Apple Home. Everything works in the Wyze app just not through Homebridge. 
I upgraded to each new update (5.36 being the latest) and I still can’t get anything to work. I downgraded to my last stable build of 5.26 and still nothing will load. 
Am I alone here?

**Comment by jfarmer08** [comment]
A nothing works BUG does not help. Can you enable logging and see what errors you are getting? Can you tell me what else you have tried?

**Comment by sisuwest** [comment]
Here is what shows up under the Logs-

7/25/2023, 4:26:34 PMWyze Smart Home BridgeWARNINGunhandled rejection: Error: ENOENT: no such file or directory, open '/var/lib/hoobs/wyzesmarthomebridge/persist/wyze-c485d0da-e9c3-4848-8642-8cf82e125bc1.json'
7/25/2023, 4:27:06 PMWyze Smart Home BridgeWyzeERRORRequest failed: Error: Request failed with status code 403
7/25/2023, 4:27:06 PMWyze Smart Home BridgeWyzeERRORResponse (Forbidden): ""
7/25/2023, 4:27:06 PMWyze Smart Home BridgeWyzeERRORError getting devices: Error: Request failed with status code 403
7/25/2023, 4:28:06 PMWyze Smart Home BridgeWyzeERRORRequest failed: Error: Request failed with status code 403
7/25/2023, 4:28:06 PMWyze Smart Home BridgeWyzeERRORResponse (Forbidden): ""
7/25/2023, 4:28:06 PMWyze Smart Home BridgeWyzeERRORError getting devices: Error: Request failed with status code 403
7/25/2023, 4:29:06 PMWyze Smart Home BridgeWyzeERRORRequest failed: Error: Request failed with status code 403
7/25/2023, 4:29:06 PMWyze Smart Home BridgeWyzeERRORResponse (Forbidden): ""
7/25/2023, 4:29:06 PMWyze Smart Home BridgeWyzeERRORError getting devices: Error: Request failed with status code 403
7/25/2023, 4:29:26 PMWyze Smart Home BridgeWARNINGunhandled rejection: Error: ENOENT: no such file or directory, open '/var/lib/hoobs/wyzesmarthomebridge/persist/wyze-c485d0da-e9c3-4848-8642-8cf82e125bc1.json'
7/25/2023, 4:30:06 PMWyze Smart Home BridgeWyzeERRORRequest failed: Error: Request failed with status code 403
7/25/2023, 4:30:06 PMWyze Smart Home BridgeWyzeERRORResponse (Forbidden): ""
7/25/2023, 4:30:06 PMWyze Smart Home BridgeWyzeERRORError getting devices: Error: Request failed with status code 403

**Comment by jfarmer08** [comment]
Looks like you need to set up the API Key and Key ID in your config. The documents still needs to be updated, but wyze is forcing this change. MFA is no longer supported. 

https://github.com/jfarmer08/homebridge-wyze-smart-home
https://developer-api-console.wyze.com/#/apikey/view

**Comment by sisuwest** [comment]
That did it! Thank you.
