### ISSUE TITLE
Request support for new WyzeCam OG

### ISSUE THREAD

**Issue by pauldonahue** [jfarmer08/homebridge-wyze-smart-home#133]
**Is your feature request related to a problem? Please describe:**
I am getting consistent messages in my Homebridge about my new WyzeCam OG not being supported.

`[7/28/2023, 7:29:02 PM] [Wyze] Camera (Model: GW_GC1 (Mac: GW_GC1_D03******* (Name: Trailer2) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found`

**Describe the solution you'd like:**
Support for the "new" WyzeCam OG

**Describe alternatives you've considered:**

**Additional context:**

**Comment by jfarmer08** [comment]
Does the cam work with the on/off control?

**Comment by iamvidoq** [comment]
I recently got an OG and an OG zoom and the on/off doesn't work for either of them. I don't care about using cameras in homebridge but the log clutter is annoying.

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.6
