### ISSUE TITLE
Request to have Floodlight Pro added

### ISSUE THREAD

**Issue by jscherry** [jfarmer08/homebridge-wyze-smart-home#134]
**Is your feature request related to a problem? Please describe:**
no
**Describe the solution you'd like:**
add floodlight pro. be able to control the floodlights and use motion sensor

[Wyze] Camera (Model: LD_CFP (Mac: LD_CFP_D03F276D1794 (Name: Floodlight Pro) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found

**Comment by jfarmer08** [comment]
The only support that should be working is on/off. Does that work for this camera?

**Comment by jscherry** [comment]
The on/off doesn’t work?
