### ISSUE TITLE
Can't control Wyze Lock Bolt YD_BT1 via Homekit

### ISSUE THREAD

**Issue by c0nstantinator** [jfarmer08/homebridge-wyze-smart-home#136]
**Describe The Bug:**
Trying to lock/unlock Wyze Lock Bolt using Homekit, it's changed the status (Locked/Unlocked) in Homekit, but the actual Lock Bolt does nothing. 

**To Reproduce:**

**Expected behavior:**
Homekit to lock/unlock wyze lock bolt

**Logs:**

```
[8/4/2023, 12:04:56 PM] [Wyze] Lock (Model: YD_BT1 (Mac: YD_BT1.095f8cb000ed72b829a0a34b657486e4 (Name: Front Door) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found
```

**Plugin Config:**

```json
 {
            "name": "Wyze",
            "username": "XXX",
            "password": "XXX",
            "keyId": "XXX",
            "apiKey": "XXX",
            "mfaCode": "XXX",
            "refreshInterval": 60000,
            "entryExitDelay": 30,
            "showAdvancedOptions": false,
            "logging": "none",
            "excludeMacAddress": false,
            "excludedeviceType": false,
            "platform": "WyzeSmartHome"
        },
```

**Screenshots:**

**Environment:**

Homebridge v1.6.1
MacOS

**Comment by carTloyal123** [comment]
There may be some technical limitations here since the Wyze lock bolt works primarily over Bluetooth (maybe even exclusively over BT) if that is the case this will likely require a large technical overhaul. I am curious if you are able to unlock this lock from anywhere over an internet connection or indeed you must be close to it?

**Comment by c0nstantinator** [comment]
You’re right. I can unlock only when nearby via BT… On Aug 7, 2023, at 7:30 PM, carTloyal123 ***@***.***> wrote:﻿
There may be some technical limitations here since the Wyze lock bolt works primarily over Bluetooth (maybe even exclusively over BT) if that is the case this will likely require a large technical overhaul. I am curious if you are able to unlock this lock from anywhere over an internet connection or indeed you must be close to it?

**Comment by carTloyal123** [comment]
I know some homebridge plugins actually do use bluetooth like the switchbot plugin but I am not sure how complicated this gets and there is no infrastructure in place in this wyze plugin for bluetooth. I would say this will not be completed anytime soon unless @jfarmer08 has some insight I am not aware of. It could be done if someone has already reverse engineered the bluetooth communication between phone and wyze lock but I doubt that is known yet

**Comment by c0nstantinator** [comment]
Got it. Its helpful. Thanks for the insights. Appreciate that. On Aug 8, 2023, at 9:28 AM, carTloyal123 ***@***.***> wrote:﻿
I know some homebridge plugins actually do use bluetooth like the switchbot plugin but I am not sure how complicated this gets and there is no infrastructure in place in this wyze plugin for bluetooth. I would say this will not be completed anytime soon unless @jfarmer08 has some insight I am not aware of. It could be done if someone has already reverse engineered the bluetooth communication between phone and wyze lock but I doubt that is known yet
