### ISSUE TITLE
Error: Request failed with status code 403

### ISSUE THREAD

**Issue by Adolflo** [jfarmer08/homebridge-wyze-smart-home#140]
Hello, 

Can you help solve what is wrong with the configu please:

Config:

    "platform": "WyzeSmartHome",
    "name": "Wyze",
    "username": "myemail",
    "password": "mypass",
    "keyId": "mykey",
    "apikey": "myapi",
    "refreshInterval": 60000,
    "logging": "debug"
}

Log shows:

8/17/2023, 5:28:45 PMWyze Smart Home Bridge starting
8/17/2023, 5:28:56 PMWyze Smart Home BridgeLoaded plugin 'homebridge-wyze-smart-home'
8/17/2023, 5:28:56 PMWyze Smart Home BridgeLoading 1 platforms...
8/17/2023, 5:28:56 PMWyze Smart Home BridgeWyzeRefreshing devices...
8/17/2023, 5:28:57 PMWyze Smart Home BridgeBridge is running on port 51836.
8/17/2023, 5:28:57 PMWyze Smart Home BridgeWyzePerforming request: user/login
8/17/2023, 5:28:57 PMWyze Smart Home BridgeWyzeRequest config: {"method":"POST","url":"user/login","data":{"email":"myemail","password":"mypass"},"baseURL":"https://auth-prod.api.wyze.com","headers":{"x-api-key":"myapi","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15"}}
8/17/2023, 5:28:58 PMWyze Smart Home BridgeWyzeERRORRequest failed: Error: Request failed with status code 403
8/17/2023, 5:28:58 PMWyze Smart Home BridgeWyzeERRORResponse PerformRequest (Forbidden): {"URL":"https://support.wyze.com/hc/en-us/articles/16129834216731-Creating-an-API-Key"}
8/17/2023, 5:28:58 PMWyze Smart Home BridgeWyzeERRORError getting devices: Error: Request failed with status code 403
8/17/2023, 5:29:58 PMWyze Smart Home BridgeWyzeRefreshing devices...
8/17/2023, 5:29:58 PMWyze Smart Home BridgeWyzePerforming request: user/login

May you please let me know what needs to be fixed, cameras I am using is V3

**Comment by jfarmer08** [comment]
You should replace "keyId": "mykey" with 
"apiKey":"mykey"

**Comment by Adolflo** [comment]
No, I installed on my cameras RTSP and run them that way true Apple Home

**Comment by jfarmer08** [comment]
Ok. Just too note this plugin didn't support camera streams.
