### ISSUE TITLE
Wyze Sprinkler Support Please !!

### ISSUE THREAD

**Issue by Infallibleman** [jfarmer08/homebridge-wyze-smart-home#143]
**Is your feature request related to a problem? Please describe:**
Please add Wyze Sprinkler support

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by jfarmer08** [comment]
I can only add hardware that I own.

**Comment by AlienInCA** [comment]
Another vote for supporting the Sprinkler

**Comment by jfarmer08** [comment]
I know others have looked at this before, but if someone wants to share it with me then I will see what I can find. 

Wyzeapi @ gmail . Com

**Comment by nathcarr55** [comment]
> I know others have looked at this before, but if someone wants to share it with me then I will see what I can find.
> 
> Wyzeapi @ gmail . Com

Shared!

**Comment by jfarmer08** [comment]
I couldn't do anything with it.

**Comment by dmkjr** [comment]
> I couldn't do anything with it.

What exactly was sent?  I have seen a few different repositories that are working on Wyze items but no one that is putting together the information from the API has a sprinkler.

**Comment by jfarmer08** [comment]
I didn't see any traffic that I could use. I also looked at the android app.
