### ISSUE TITLE
Should the floodlight accessory show up as a homekit light?

### ISSUE THREAD

**Issue by tabrindle** [jfarmer08/homebridge-wyze-smart-home#146]
**Describe Your Problem:**

I got the plug-in installed and working, however  the only accessories that showed up in homebridge were on off switches for the camera. Should the floodlight show up as another accessory? I see some references in the code to floodlight control but I don’t see anything like that in the ui. Is there any special config I might be missing? I have just the minimum required documented config set up for user/pass/api key/Id. 

**Logs:**
If this is supposed to work, I’ll happily add some context here to help debug. I’ve written a couple homebridge plugins, may be able to help out here with some guidance. 
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by jfarmer08** [comment]
I am working on added the floodlight.

**Comment by tabrindle** [comment]
Great to hear! Let me know if there’s anything I can do to help. Happy to test or contribute.

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.1

**Comment by tabrindle** [comment]
This is awesome! I’ll check it out later today.

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.4

**Comment by brax10ward** [comment]
> [`v0.5.37-alpha.4` (release)](https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.4)

@jfarmer08 could you advise on how to setup the floodlights?
