### ISSUE TITLE
Request failed: Error: Request failed with status code 403

### ISSUE THREAD

**Issue by waverider1116** [jfarmer08/homebridge-wyze-smart-home#149]
**Describe The Bug:**
I have installed and uninstalled the plug-in and added my configuration file and I'm still getting the 403 error. I copy and pasted the keys, ids, and password.

**To Reproduce:**
I have installed and uninstalled the plug-in and added my configuration file and I'm still getting the 403 error

**Expected behavior:**
The plug-In to pickup the API and grab my device list

**Logs:**
9/3/2023, 12:57:15 PMWyze Smart Home BridgeWyzeERRORRequest failed: Error: Request failed with status code 403
9/3/2023, 12:57:15 PMWyze Smart Home BridgeWyzeERRORResponse PerformRequest (Forbidden): {"URL":"https://support.wyze.com/hc/en-us/articles/16129834216731-Creating-an-API-Key"}
9/3/2023, 12:57:15 PMWyze Smart Home BridgeWyzeERRORError getting devices: Error: Request failed with status code 403
9/3/2023, 12:58:15 PMWyze Smart Home BridgeWyzeERRORRequest failed: Error: Request failed with status code 403
9/3/2023, 12:58:15 PMWyze Smart Home BridgeWyzeERRORResponse PerformRequest (Forbidden): {"URL":"https://support.wyze.com/hc/en-us/articles/16129834216731-Creating-an-API-Key"}
9/3/2023, 12:58:15 PMWyze Smart Home BridgeWyzeERRORError getting devices: Error: Request failed with status code 403

**Plugin Config:**

{
    "platform": "WyzeSmartHome",
    "name": "Wyze",
    "username": "myemail@test.com",
    "password": "mypass",
    "keyId": "myId",
    "apikey": "mykey",
    "refreshInterval": 60000
}

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.5.36
* **Homebridge Version**: 4.3.0 
* **Node.js Version**: 16.20.2
* **NPM Version**: 
* **Operating System**: macOS

**Comment by sisuwest** [comment]
I'm similar but I get a code 400. This worked until I reinstalled Homebridge today. Upon re-adding my plugins and adding the UN, PW, Key and API code I get this-

[10/09/2023, 12:53:58] [Wyze] Request failed: Error: Request failed with status code 400
[10/09/2023, 12:53:58] [Wyze] Response PerformRequest (Bad Request): {"description":"Invalid credentials, please check username, password, keyid or apikey","requestId":"d1787ae7-9c25-430e-9a3a-e8240a03e1ff","errorCode":1000}
[10/09/2023, 12:53:58] [Wyze] Error getting devices: Error: Request failed with status code 400

I want to say it's the API Key which seems to be hidden behind some asterisks. 

************wxI9

Ideas?

**Comment by RMCob** [comment]
I also had similar problems. Upon inspection of the Api_key I discovered that the api_key that was generated contained characters that are 'special' to the Linux shell command - ex: '*', '|' (vertical bar/pipe symbol), and ';'. When I regenerated the api_key and key_id to ensure no special chars were included everything worked properly.

**Comment by sisuwest** [comment]
That worked for me, @RMCob  Thanks. I had tried that before but it still showed me the special characters instead.

**Comment by saadatorama** [comment]
Having same issue, randomly started after latest update. I am not using an API key and authenticating with username and password.
