### ISSUE TITLE
Wyze Cam Outdoor, Model HL_WCC2 not supported

### ISSUE THREAD

**Issue by WSewell** [jfarmer08/homebridge-wyze-smart-home#151]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by afridorian** [comment]
I’m getting the same error message
“Camera (Model: HL_WCO2 not supported submit a request to…”

The issue I’m having is that this message prints constantly to the Homebridge logs, even when I exclude the MAC address in the settings. Any ideas on how to get this to stop and/or support the Outdoor Cam v2?
