### ISSUE TITLE
Lock Support Model: YD_BT1 (Wyze Lock Bolt)

### ISSUE THREAD

**Issue by russellbar** [jfarmer08/homebridge-wyze-smart-home#152]
**Is your feature request related to a problem? Please describe: Wyze Door lock model YD_BT1 does not work**

**Describe the solution you'd like: I'd like added support for this lock**

**Describe alternatives you've considered: If there are any workarounds I'd love to know them. It is a Bluetooth device so I am not sure if it is possible but my Pi does have Bluetooth so I feel like it should be. I've considered using the camera as a work around. I know pairing it means it connects to Wi-Fi through the camera so if you can add lock functionality through that, that would work as well.**

**Additional context:**

**Comment by WelshMcSpicy** [comment]
I would like this too. Thanks.

**Comment by anderfrank** [comment]
The Wyze Lock Bolt is bluetooth only so not sure it will be controllable by Homebridge.

**Comment by jfarmer08** [comment]
Not much I can do at this time.
