### ISSUE TITLE
Support for Video Doorbell Model: GW_BE1

### ISSUE THREAD

**Issue by russellbar** [jfarmer08/homebridge-wyze-smart-home#153]
**Is your feature request related to a problem? Please describe: This is a support request for the Wyze doorbell pro**

**Describe the solution you'd like: Id like support for this video doorbell including support for any associated devices like the Bluetooth lock bolt you can pair to it.**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by carTloyal123** [comment]
See this issue related to Gwell based cameras include the video doorbell pro: [VDP2 support](https://github.com/jfarmer08/homebridge-wyze-smart-home/issues/182#issuecomment-1942133497)
