### ISSUE TITLE
Wyze devices not appearing

### ISSUE THREAD

**Issue by citizenleroy** [jfarmer08/homebridge-wyze-smart-home#158]
Hi! 

I installed the bridge and configured the plug in with MFA code. Bridge installs in HomeKit, but devices (thermostat, for ex.) do not appear in HomeKit?

MFA in Wyze is configured with cellular text. I believe I’m doing something wrong with configuring the MFA in the plug in? Timing, when to insert, etc? Can someone please assist? Thank you for your help!! I do have other bridges working OK.

citizenleroy :)

**Comment by jfarmer08** [comment]
MFA is not supported. You need to use api key instead

**Comment by citizenleroy** [comment]
That was it! Advanced configured with keyid, api key, and mfa code fields.

I now have the thermostat which is what I needed in HomeKit! Thanks again jfarmer08!! :)

**Comment by citizenleroy** [comment]
Thanks again!! :)
