### ISSUE TITLE
Camera tiles in HomeKit and Homebridge accessories tab showing 2 on/off switches after upgrade to 0.5.37-alpha.1

### ISSUE THREAD

**Issue by smcallah** [jfarmer08/homebridge-wyze-smart-home#163]
**Describe The Bug:**

After upgrading to 0.5.37-alpha.1 I just noticed today that all of my cameras (v2, v3, and WCO) now have 2 on/off switches under each device tile in HomeKit on iOS 17.  I have attached screenshots of a camera in HomeKit to show how they look.

Also, cameras that previously showed no response have a switch that is off and a switch that is on.  Online cameras have 2 switches in the on position.

I'm running Homebridge in insecure mode to control devices direct from the accessories tab as well and cameras have 2 separate switch tiles present there too, so it's not just a HomeKit on Apple issue it appears.

I have not changed the plugin configuration (except setting logging to debug) and have not added/removed any cameras or other devices to the Wyze app since I first installed wyze-smart-home.

I have restarted the wyze-smart-home child bridge, as well as Homebridge service, and both switches per camera still show up.  At restart, it says that 23 cached devices are loaded, which appears to be the number I should have.  I would expect it to show 34, as I have 11 cameras, if it were loading the cameras twice somehow.

**To Reproduce:**

**Expected behavior:**

Only one switch should show per camera

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
{
"name": "Wyze",
"username": "xxxxx",
"password": "password",
"keyId": "the keyId",
"apiKey": "the apiKey",
"refreshInterval": 60000,
"entryExitDelay": 30,
"showAdvancedOptions": true,
"logging": "none",
"excludeMacAddress": false,
"excludedeviceType": false,
"_bridge": {
"username": "DE:AD:BE:EF:B0:0B",
"port": 58172
},
"platform": "WyzeSmartHome"
}
```

**Screenshots:**

<img width="585" alt="IMG_2279" src="https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/6232531/c204b183-840e-4389-8f62-84cdf8432b89">
<img width="585" alt="IMG_2280" src="https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/6232531/ee51bcd8-91d5-4459-9cad-4d99e7ce48ba">
<img width="585" alt="IMG_2281" src="https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/6232531/34cc3fe8-42a4-4ca4-95b6-b9682f7222b0">

**Environment:**

* **Plugin Version**: 0.5.37-alpha.1
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 18.18.0
* **NPM Version**: 9.5.1
* **Operating System**: Debian GNU/Linux Bullseye (11) on Raspberry Pi 4 8GB

**Comment by anderfrank** [comment]
I had this problem as well. Ended up needing to disable the plugin and then remove all cached accessories from Homebridge. Once I re-enabled the plugin and restarted homebridge the duplicates went away. There may be another fix to resolve this but I could not find one, even downgrading to the 0.5.36 build did not remove them.

**Comment by jfarmer08** [comment]
Sounds about right. I have not found a good way to remove cache automatically.

**Comment by ExioStar** [comment]
FWIW, I also had this issue, and it also required restarting the "hub" devices in my home (the HomePod minis in my case).

**Comment by sreenath87** [comment]
Same Issue here. Unable to fix it.

**Comment by ceedveed** [comment]
> I had this problem as well. Ended up needing to disable the plugin and then remove all cached accessories from Homebridge. Once I re-enabled the plugin and restarted homebridge the duplicates went away. There may be another fix to resolve this but I could not find one, even downgrading to the 0.5.36 build did not remove them.

Thanks this worked for me. I had all my Wyze cameras duplicated. All the steps above are needed. I tried to do less and it wouldn't work.

**Comment by smcallah** [comment]
Disabling the plugin, deleting cached accessories, re-enabling and restarting HB also resolved the dual camera switch issue for me. I was waiting, but didn't do this until wyze bridge started a crash loop because of something wrong with my cached accessories, which I believe to be a color bulb.
