### ISSUE TITLE
Wyze Api not working

### ISSUE THREAD

**Issue by zswuwing** [jfarmer08/homebridge-wyze-smart-home#164]
**Describe The Bug:**
When i tried to lock the door in homekit, homekit said it is locked but it is not and i got these errors
API response GetLockInfo: {"ReqID":"dfba0e901a","ErrNo":"17001","ErrMsg":"PARAM_TIMESTAMP_INVALID"}

API response GetLockInfo: {"ReqID":"dfba0e901a","ErrNo":"17001","ErrMsg":"PARAM_TIMESTAMP_INVALID"}

**To Reproduce:**
Not Sure how to reproduce. Looks like a timestamp format thing

**Expected behavior:**

**Logs:**
[9/27/2023, 4:22:47 PM] [Wyze] API response GetLockInfo: {"ReqID":"f9ba87b56f","ErrNo":"17001","ErrMsg":"PARAM_TIMESTAMP_INVALID"}
[9/27/2023, 4:22:47 PM] [Wyze] API response GetLockInfo: {"ReqID":"dfba87f3fa","ErrNo":"17001","ErrMsg":"PARAM_TIMESTAMP_INVALID"

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
{
    "name": "Wyze",
    "username": "",
    "password": "!",
    "keyId": "",
    "apiKey": "",
    "mfaCode": "051505",
    "refreshInterval": 60000,
    "entryExitDelay": 5,
    "showAdvancedOptions": true,
    "logging": "debug",
    "excludeMacAddress": true,
    "filterByMacAddressList": [
        "YD.GW1.036a78a8a7ee3039cfbbcc49af40ec26",
        "YD.GW1.66f5d4797333376e90b0d294cc1f0a01"
    ],
    "excludedeviceType": true,
    "filterDeviceTypeList": [
        "S1Gateway"
    ],
    "_bridge": {
        "username": "0E:86:90:4D:46:E3",
        "port": 33934
    },
    "platform": "WyzeSmartHome"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.5.37
* **Homebridge Version**:  4.50.5
* **Node.js Version**:  20.7
* **NPM Version**: 
* **Operating System**:  Docker in Qnap

**Comment by jfarmer08** [comment]
Is your date/time correct on the machine?

**Comment by zswuwing** [comment]
@jfarmer08 seems correct on my qnap system and docker container

**Comment by zswuwing** [comment]
@jfarmer08 any other though?

**Comment by jfarmer08** [comment]
Are you using this plugin or a custom one. I ask because I don't have a version 37

**Comment by zswuwing** [comment]
> Are you using this plugin or a custom one. I ask because I don't have a version 37

@jfarmer08 It is my custom version to fix something. You are rigth it is my system time not up to date. Thank you so much!!!!
