### ISSUE TITLE
Light switch status off when device is on >>

### ISSUE THREAD

**Issue by wbizreh** [jfarmer08/homebridge-wyze-smart-home#165]
**Describe The Bug:**

when wyze light switch turns on it shows in homekit as switch is on but after few seconds it changes automatically to off in homekit even though the device did not turn off.
no log appear in homebridge when toggeling device on or off. 
HB v. 1.6.1
Node.js Version | v18.17.1
plug in V0.5.37 alpha.2

Node.js Version	[v18.17.1](https://homebridge.io/w/JTKEF)

**Comment by jfarmer08** [comment]
Can you upgrade to version 3 and report back

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.4

**Comment by wbizreh** [comment]
Still same issue persist. I am having to revert to v0.5.35 to get the issue resolved

**Comment by jfarmer08** [comment]
The code is the same for both version within the aspect of the WyzeSwitch. So I am not sure what is happening. The latest release seems to work for me.

**Comment by jfarmer08** [comment]
I did find the issue. I will release it soon.

**Comment by wbizreh** [comment]
Awesome, thanks a bunch

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.37-alpha.6

**Comment by wbizreh** [comment]
The new update is working perfectly. Thank you for the awesome work!!
