### ISSUE TITLE
Request support for WYZEDB3 (Wyze Doorbell)

### ISSUE THREAD

**Issue by anderfrank** [jfarmer08/homebridge-wyze-smart-home#166]
**Is your feature request related to a problem? Please describe:**
[Wyze] Camera (Model: WYZEDB3  not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found

**Describe the solution you'd like:**
Add support for WYZEDB3 camera

**Comment by anderfrank** [comment]
Disregard, I see the doorbell does not have an on/off option in the app.

Is it possible to silence this notification so that it does not spam the logs?

**Comment by socalcal** [comment]
I have the plug-in loaded as a child bridge and after the WYZEDB3 error hits, it closes the child bridge, then reloads and repeats.

**Comment by BBfly1** [comment]
Problem description:
After updating to "homebridge-wyze-smart-home v0.5.37-alpha.4", this is the message I am getting  ... "[17/10/2023, 15:27:24] [Wyze] Camera (Model: WYZEDB3 (Mac: xxxxxxxxxxxx (Name: Cam-FrDoorbell-Wyze-v1) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found".

Describe the solution you'd like:
Add support for WYZEDB3 camera (Wyze Video Doorbell v1)

Thanks:

**Comment by carTloyal123** [comment]
@BBfly1 is this resolved with the latest update to the bridge?

**Comment by BBfly1** [comment]
Yes, this is resolved.

Thanks,
bb
