### ISSUE TITLE
Cameras shown as switches 

### ISSUE THREAD

**Issue by sreenath87** [jfarmer08/homebridge-wyze-smart-home#168]
All my cameras are shown as switches. 

Installed the latest version of Plugin on a new setup of Homebridge and i experience the issue. 

Would expect the cameras to show up as cameras with thumbnail.

Tried to remove cachedAccessories and tried again with same issue. 

{
            "name": "Wyze",
            "username": "email@email.com",
            "password": "password@password",
            "keyId": "RANDOM-STRING-AS-KEY-FROM-WYZE",
            "apiKey": "API-KEY-FROM-WYZE",
            "refreshInterval": 5000,
            "entryExitDelay": 30,
            "showAdvancedOptions": false,
            "logging": "none",
            "excludeMacAddress": false,
            "excludedeviceType": false,
            "_bridge": {
                "username": "MAC:ADDREESS",
                "port": 40686
            },
            "platform": "WyzeSmartHome"
        }

```
![alt text](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/61849389/81c8e299-4637-4707-b2fc-93cdb3b99277.png)

![alt text](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/61849389/12d433a7-cecf-4bfe-ba37-6a10f4aa4046.png)


**Environment:**

 v0.5.37-alpha.2
Homebridge Version: [v1.6.1]
Node.js Version v18.18.0
Operating System:  Docker

**Comment by jfarmer08** [comment]
Camera video feed is not supported
