### ISSUE TITLE
Support request for S1Gateway

### ISSUE THREAD

**Issue by lewis6681** [jfarmer08/homebridge-wyze-smart-home#171]
**Is your feature request related to a problem? Please describe:**

I get the following error when trying to enable the homebridge plugin: S1Gateway (Model: GW3U (Mac: undefined (Name: undefined) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added.
**Describe the solution you'd like:**

Can you please add support for S1Gateway (Model: GW3U)
**Describe alternatives you've considered:**

**Additional context:**

**Comment by ianmabie** [comment]
I think same my error:

`S1Gateway (Model: GW3U (Mac: 7C78B22C9E2D (Name: Wyze Sense Hub) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added.`

**Comment by jfarmer08** [comment]
Yes the HSM alarm is supported. I will fix the logs, but for the latest release you will need too change your config to enable it.
