### ISSUE TITLE
Add Support for Wyze Lock Bolt YD_BT1

### ISSUE THREAD

**Issue by dan0-gh** [jfarmer08/homebridge-wyze-smart-home#181]
**Is your feature request related to a problem? Please describe:**

Lock appears in HomeKit but always shows as locked and does not respond to tap.
Getting persistent messages in logs, "Lock (Model: YD_BT1 (Mac: YD_BT1.xx (Name: Door Lock) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added. If no issues are found"

**Describe the solution you'd like:**

Please add support for Wyze Lock Bolt

**Describe alternatives you've considered:**

None

**Additional context:**

[Wyze Lock Bolt](https://www.wyze.com/products/wyze-lock-bolt)

**Comment by Lostboy66** [comment]
Would also like to see this.

**Comment by carTloyal123** [comment]
Added to feature requests here: #224

**Comment by jwlynch008** [comment]
is there any progress in adding the Wyze Lock Bolt?
