### ISSUE TITLE
Updated Homebridge UI to the latest version and now all of my Wyze devices are offline.

### ISSUE THREAD

**Issue by vascott1** [jfarmer08/homebridge-wyze-smart-home#184]
**Describe Your Problem:**
Updated Homebridge UI to the latest version (homebridge-config-ui-x v4.51.0) and now all of my Wyze devices are offline. Have confirmed that my Key Id, Api Key are correct as well as my username and password. I have rebooted and power cycled my Pi. 
**Logs:**

Show the Homebridge logs here, remove any sensitive information.

`[23/10/2023, 19:42:12] [wyze-smart-home] Request failed: AxiosError: Request failed with status code 400
[23/10/2023, 19:42:12] [wyze-smart-home] Response PerformRequest (Bad Request): {"description":"Invalid credentials, please check username, password, keyid or apikey","requestId":"xxxxxx","errorCode":1000}`

**Plugin Config:**

        {
            "name": "wyze-smart-home",
            "username": "xxxxx@gmail.com",
            "password": "xxxx",
            "keyId": "xxxx",
            "apiKey": "xxxx",
            "refreshInterval": 60000,
            "hms": false,
            "showAdvancedOptions": true,
            "apiLogEnabled": false,
            "logLevel": "none",
            "excludeMacAddress": true,
            "filterByMacAddressList": [
                "7C78B2705140"
            ],
            "excludedeviceType": true,
            "filterDeviceTypeList": [
                "Camera"
            ],
            "platform": "WyzeSmartHome"
        },

**Screenshots:**

**Environment:**

* **Plugin Version**: v0.5.37-alpha.4
* **Homebridge Version**: 1.6.1
* **Node.js Version**: v18.16.0
* **NPM Version**: 9.5.1
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by jfarmer08** [comment]
I mean the error says something different. 🤷‍♂️🤷‍♂️

**Comment by vascott1** [comment]
Sorry to be confusing. Not intentional of course. 

The devices are all offline because the plugin cannot log into my account. The only change made was upgrading homebridge UI and a restart. The error below just repeats over and over again. I confirmed that all the information in the config matches What I see on the API Key page from Wyze and does not expire until 3 July 2024.

I considered backing out to v0.5.36 and see if that resolved the issue but thought there might be some interest if I had found an issue in the latest build of 5.37

If there is more information I can supply, let me know. And if there is any action you would like me to try I can do that :)



[23/10/2023, 20:11:32] [wyze-smart-home] Error getting devices: AxiosError: Request failed with status code 400
[23/10/2023, 20:12:32] [wyze-smart-home] Request failed: AxiosError: Request failed with status code 400
[23/10/2023, 20:12:32] [wyze-smart-home] Response PerformRequest (Bad Request): {"description":"Invalid credentials, please check username, password, keyid or apikey","requestId":"fce9430d-590a-4f57-a921-ae7954533cca","errorCode":1000}
[23/10/2023, 20:12:32] [wyze-smart-home] Error getting devices: AxiosError: Request failed with status code 400

**Comment by jfarmer08** [comment]
Have you checked this ticket out https://github.com/jfarmer08/homebridge-wyze-smart-home/issues/149?

**Comment by vascott1** [comment]
That worked! I regenerated the key and all is well now. Easy fix. 

Thanks for the guidance.
