### ISSUE TITLE
Support for Wyze Cam Pan v1, v2, and v3 Feed.

### ISSUE THREAD

**Issue by yodaluca23** [jfarmer08/homebridge-wyze-smart-home#191]
**Is your feature request related to a problem? Please describe:**

I am frustrated that I can only turn my Wyze cam pan V3 on and off...

**Describe the solution you'd like:**

Add support for as many things as HomeKit supports, ie. Live Streaming, Paning, Past Recordings, etc.

**Describe alternatives you've considered:**

Only adding Live Streaming

**Comment by jfarmer08** [comment]
If you can find a way to do what your asking I would accept a pull request.

**Comment by yodaluca23** [comment]
Hmmm, looks like the most efficient and easiest way would be to just use RTSP, but as mentioned [here,](https://github.com/noelportugal/wyze-node/issues/2#issuecomment-1089844571) it's been removed from the main firmware channel (meaning people would have to flash other firmware, killing off basically every other feature)... Or reverse engineer the web view, as suggested [here](https://github.com/jfarmer08/homebridge-wyze-smart-home/issues/80).

**Comment by yodaluca23** [comment]
@jfarmer08 Or I just found this https://github.com/kroo/wyzecam and this https://github.com/mrlt8/docker-wyze-bridge that look promising, it would take some work, as it's programed in Python, but we might be able to make it work, thoughts?

**Comment by jfarmer08** [comment]
You would need to use python in JavaScript which is possible or translate tutk from python to JavaScript

Neither one is a small task. Using rtsp or the web app would not allow for the additional controls that you mentioned.

**Comment by afridorian** [comment]
On November 7th, Wyze released the web portal where you can see camera feeds from a url instead of the app. Could that be used to pull camera feeds into Home?

**Comment by jfarmer08** [comment]
Only for cam plus users. I am not sure what it would help.

**Comment by yodaluca23** [comment]
Yea, if I was cam plus, I'd like to dive into that, and see if I could reverse engineer it, or even just find how to decode the stream url or something...

**Comment by afridorian** [comment]
@yodaluca23 I have cam plus and i’d be willing to share logs or whatever is needed to get it going if that’s something you want to play with.

**Comment by carTloyal123** [comment]
This would be a large undertaking, the long term future of this plugin might support video streaming but for now these features are less feasible.

@jfarmer08 it sounds like we can close this issue as basically not planned. Do you have a place you are tracking long term features for the plugin? If so this would fit more cleanly in that type of planning

**Comment by carTloyal123** [comment]
@yodaluca23 look into docker-wyze-bridge paired with Scrypted to get wyze video streams into homekit

**Comment by jfarmer08** [comment]
@carTloyal123 I trust your opinion.

**Comment by carTloyal123** [comment]
Please see scrypted, docker-Wyze bridge or Cryze for video support of Wyze cameras. Closing this as not planned since this plugin is about control and status and not well suited for feed streams at the moment.
