### ISSUE TITLE
Wyze account with Google login?

### ISSUE THREAD

**Issue by acodring** [jfarmer08/homebridge-wyze-smart-home#195]
Wyze plugin settings include username, password, key id, api key…

I used my google account to create my Wyze account so I don’t have a Wyze password. Should this plugin still work for me?

If my config details and logs would help I can try again tomorrow. Logs are just “too many attempts, try again later…” now. 

I created an API key on the Wyze developer site. 
I assumed that I could just enter my key id and api key and ignore the username/password. That didn’t work. 

Then tried adding my username (email), still with no password. Did not work. 

I don’t want to enter my Google password in the config and even if I did I don’t imagine that could work if the settings expects Wyze account credentials. 

Have I misunderstood something?

**Comment by jfarmer08** [comment]
I have not tested with using google to login.

**Comment by acodring** [comment]
Ok. Thanks. I’ll create a regular account instead.
