### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Peltier36** [jfarmer08/homebridge-wyze-smart-home#196]
*Will not allow me to login after all credentials are inserted: **

**Logs:**
11/13/2023, 3:32:43 PMWyze Smart Home BridgeWyzeERRORRequest failed: AxiosError: Request failed with status code 403
11/13/2023, 3:32:43 PMWyze Smart Home BridgeWyzeERRORResponse PerformRequest ([object Object]): {"URL":"https://support.wyze.com/hc/en-us/articles/16129834216731-Creating-an-API-Key"}
11/13/2023, 3:32:43 PMWyze Smart Home BridgeWyzeERRORError getting devices: AxiosError: Request failed with status code 403
11/13/2023, 3:32:46 PMmyQ BridgemyQERRORmyQ API error: Forbidden API call. This error is typically due to an offline or unavailable myQ device
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**
Hoobs
* **Plugin Version**:
* 0.5.37
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by jfarmer08** [comment]
Can you paste your config?

**Comment by loveland1988** [comment]
Starting a couple weeks ago, I was getting a similar error.   Initially, I hadn't added an API key to my config (worked for months without one) so I tried that, and it fixed it.  I did have to remove/re-add the Wyze accessories to Apple Home.

**Comment by carTloyal123** [comment]
@Peltier36 has this been resolved?

**Comment by carTloyal123** [comment]
Should be resolved in latest release, and stale.
