### ISSUE TITLE
Error getting devices: Error: ENOENT:

### ISSUE THREAD

**Issue by daftpac** [jfarmer08/homebridge-wyze-smart-home#198]
**Describe The Bug:**
 WyzeERRORError getting devices: Error: ENOENT: no such file or directory, open '/var/lib/hoobs/wyzesmarthomebridge/persist/wyze-5f8a0cb2-bd25-59a3-8f4d-b343199f476f.json'.

**To Reproduce:**
 issues occurs when saving the config

**Expected behavior:**
 for the plugin to pull the devices

**Logs:**

```
11/18/2023, 12:43:44 PMWyze Smart Home Bridge starting
11/18/2023, 12:43:55 PMWyze Smart Home BridgeLoaded plugin 'homebridge-wyze-smart-home'
11/18/2023, 12:43:56 PMWyze Smart Home BridgeLoading 1 platforms...
11/18/2023, 12:43:56 PMWyze Smart Home BridgeBridge is running on port 51826.
11/18/2023, 12:43:57 PMWyze Smart Home BridgeWyzeERRORError getting devices: Error: ENOENT: no such file or directory, open '/var/lib/hoobs/wyzesmarthomebridge/persist/wyze-5f8a0cb2-bd25-59a3-8f4d-b343199f476f.json'.
```

**Plugin Config:**

```json
{
    "platform": "WyzeSmartHome",
    "name": "Wyze",
    "username": "email",
    "password": "password",
    "refreshInterval": 60000,
    "keyId": "key",
    "apiKey": "key",
    "logging": "debug"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.5.37-alpha.7
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 16.20.2

**Comment by jfarmer08** [comment]
You can try and change the location of the stored file. 

'''"persistPath":"/filepath"'''

**Comment by mdavid6** [comment]
i had exactly the same issues i have try to change de location  like you said but do i keep the /filepath ?? or other

**Comment by carTloyal123** [comment]
@daftpac is this resolved with the latest updates to the plugin?

**Comment by jfarmer08** [comment]
@mdavid6 change it too something like '/var/lib/hoobs' for testing.

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/issues/201
