### ISSUE TITLE
Garage Door Doesn't Display in Homebridge

### ISSUE THREAD

**Issue by sisuwest** [jfarmer08/homebridge-wyze-smart-home#199]
Garage Door doesn't appear at all. I'm not talking about its status but that the device isn't even found. 

I don't know which logs you want to see...there are a lot of them. My accessories tab is huge too. Happy to send whatever you need to see. 

Running 5.37 alpha 7
Homebridge 4.53

**Comment by jfarmer08** [comment]
Did you include it in the config.

**Comment by sisuwest** [comment]
Did I include what in the config? Not sure what you're talking about. Any documentation to show me what you're talking about?

**Comment by jfarmer08** [comment]
![image](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/18117255/75457e5a-63f9-46cc-b225-d532a8f27967)

**Comment by sisuwest** [comment]
Ok, I got that added, but it still won't display in my accessories. I can see the camera but no controller. Where should it be displayed? And once it does will it just show the open/close status or can I actually open and close it from Homebridge?

**Comment by jfarmer08** [comment]
Add the MAC address of your camera to the garage door accessory in the config and then reboot. After that you should see a garage door in HomeKit. You can open and close it along with it showing the stat of the door. Some people have reported that the status has issues.

**Comment by sisuwest** [comment]
That worked. Thanks.
