### ISSUE TITLE
HL_WCO2 Works fine

### ISSUE THREAD

**Issue by hmangnx** [jfarmer08/homebridge-wyze-smart-home#205]
**Describe The Bug:**
HL_WC02 not supported submit a request
Message keeps popping up in logs. 

**To Reproduce:**
As said above

**Expected behavior:**
It is support so the error message should not appear

**Comment by hmangnx** [comment]
However, it does not work on the latest alpha version not sure why. When I downgrade one version down it works fine except for the message.

**Comment by hmangnx** [comment]
38 fixes the 403 error however like 37 alpha it doesn’t show the on/off switches for my Wyze outdoor 2 cams for some reason. It worked with version 36 before the 403 error any insights would be great. Interestingly it shows 5 devices. 2 Wyze cam v3 which work and 2 outdoor v2 cam and bridge that do not work. 

![IMG_0802](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/45419224/a000a73c-7639-4c18-b4a5-78657c3b0633)

**Comment by hmangnx** [comment]
Ok I see what is going on. You have excluded that device for some reason. I have unexcluded the device to test from inside the enums.js file and it loads fine. Thanks.

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.39

**Comment by hmangnx** [comment]
> https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.39

I think you typo’s the string for the outdoor v2. 

This is what I have that works. 

![IMG_0804](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/45419224/3a93726c-8948-464b-b107-f1c2b10c0c2d)

**Comment by jfarmer08** [comment]
Looks like I had a zero instead of a O. I just pushed a new release to correct this.
