### ISSUE TITLE
Dangerous Garage Door Opener

### ISSUE THREAD

**Issue by sisuwest** [jfarmer08/homebridge-wyze-smart-home#209]
As you are aware, the status for the garage door is unreliable. Unfortunately, it's not just a status issues. When a change in status occurs while the door is opening or closing, it will cause the door to pause. In some circumstances, it will then reverse the direction of that door without warning. No beeping, no siren, no lights just to change in direction. I nearly had the garage door closed on my car while I was pulling in this morning. This is a dangerous plug-in. If it cannot perform correctly, it needs to be disabled. It's not like a lightbulb or a plug that turns on or off. This is a heavy door that automatically closes or opens randomly. This bug needs to be fixed before this feature is re-enabled.

**Comment by jfarmer08** [comment]
Garage door is still in alpha for that reason.

**Comment by jfarmer08** [comment]
If you want to look more into this, you can start looking at P1056 and see if that reports the door state correctly.

**Comment by sisuwest** [comment]
Happy to help. I wouldn't know where to look for that. I don't see that code in the logs. 
Let me know what parts of my logs you need.

**Comment by carTloyal123** [comment]
refer to #193 for future updates on this since they are both related to Garage Door performance and alpha development
