### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by ThatOneGuy808** [jfarmer08/homebridge-wyze-smart-home#212]
There hasn't been an update since July, and the 403 bug basically broke this. I haven't seen any response from the creator really

Is there an alternative plugin for Wyze accessories that works at the moment?

**Comment by ihatemyisp** [comment]
It looks like it is an issue with the the wyze-api Node module that is preventing this from working. There is https://github.com/jfarmer08/wyze-api/pull/3 that looks to fix it though.

I might try and test everything later today if I get some time.

**Comment by jfarmer08** [comment]
Still being maintained when I have free time.

**Comment by jfarmer08** [comment]
Update has been pushed.

**Comment by ThatOneGuy808** [comment]
Oh, thank you very much! Sorry if that came off rude it just gave the impression this was dead which some projects end up being sadly. I appreciate the work you do
