### ISSUE TITLE
TypeError: devices is not iterable

### ISSUE THREAD

**Issue by adolton1** [jfarmer08/homebridge-wyze-smart-home#217]
**Describe Your Problem:**

*Edit: Sorry just saw someone posted this issue earlier today, forgot to check again before I posted. Feel free to delete.

After running into issue #208 and having to reset my password my Wyze cameras are not showing up in HomeKit and I am seeing this error in the logs.
[Wyze] Error getting devices: TypeError: devices is not iterable

A little detail of events, I got an email from Wyze like many others that I had to reset my password, which I did. I realized yesterday, duh that's why my cameras weren't showing up correctly (showing off when they were on) in HomeKit. So I updated the Wyze plugin in Homebridge and updated the password. But it still wasn't working. That's when I noticed this error in the log. I've tried deleting and getting a new Wyze API key, as well as uninstalling and reinstalling/reconfiguring the Wyze plugin in Homebridge with no luck. Once I uninstalled the plugin I was able to add the Wyze bridge back into HomeKit but none of the cameras show up now.

Any other tips or help in getting this fixed is greatly appreciated!

**Logs:**

[2/10/2024, 9:58:00 AM] [Wyze] Initializing WyzeSmartHome platform...
Setup Payload:
X-HM://0024Y1EI2BVQG
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
    ┌────────────┐     
    └────────────┘     
[2/10/2024, 9:58:00 AM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge A7FC) is running on port 51722.
[2/10/2024, 9:58:00 AM] [Wyze] Error getting devices: TypeError: devices is not iterable
[2/10/2024, 9:59:00 AM] [Wyze] Error getting devices: TypeError: devices is not iterable

**Plugin Config:**

            "name": "Wyze",
            "username": "******",
            "password": "******",
            "keyId": "******",
            "apiKey": "******",
            "refreshInterval": 60000,
            "hms": false,
            "showAdvancedOptions": false,
            "apiLogEnabled": false,
            "logLevel": "none",
            "lowBatteryPercentage": 30,
            "excludeMacAddress": false,
            "excludedeviceType": false,
            "platform": "WyzeSmartHome"

**Screenshots:**

**Environment:**

* **Plugin Version**: v0.5.42
* **Homebridge Version**: v1.7.0
* **Node.js Version**: v20.10.0
* **NPM Version**: 10.2.3
* **Operating System**: Ubuntu Focal Fossa (20.04.5 LTS)

**Comment by bunnyc1986** [comment]
I'm getting the same error.

**Comment by bunnyc1986** [comment]
dup: https://github.com/jfarmer08/homebridge-wyze-smart-home/issues/216

**Comment by jfarmer08** [comment]
Can you try version https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.43

**Comment by jfarmer08** [comment]
hopefully this helps https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.44

**Comment by carTloyal123** [comment]
Closing in favor of #216
