### ISSUE TITLE
Garage Door only supports turning on/off the camera, not the actual garage controller

### ISSUE THREAD

**Issue by Zamua** [jfarmer08/homebridge-wyze-smart-home#225]
**Describe Your Problem:**

Hello,

I installed homebridge and this plugin on a raspberry pi zero w. the plugin is able to find my wyze thermostat and my garage camera, but it is unable to view the camera feed, nor does it control the garage door. the only function for the garage door is turn on and off the camera. do i need to take further steps to enable the garage door controller functionality? i thought maybe i had to manually add the controller MAC to the config, but that didn't appear to work

**Logs:**
I redacted MAC and stuff just in case (sorry i'm a security noob)
```
[20/02/2024, 02:35:23] [Wyze] Refreshing devices...
[20/02/2024, 02:35:24] [Wyze] Found 11 device(s)
...
[20/02/2024, 02:35:24] [Wyze] [Camera] Loading accessory from cache Garage Cam (MAC: REDACTED)
[20/02/2024, 02:35:24] [Wyze] [Camera] [Privacy] Updating status of REDACTED (Garage Cam)
...
[20/02/2024, 02:35:24] [Wyze] [Thermostat] Temp: 74
[20/02/2024, 02:35:24] [Wyze] [Thermostat] Target Temp: 74
[20/02/2024, 02:35:24] [Wyze] [Thermostat] Mode Sys: auto for 3
[20/02/2024, 02:35:24] [Wyze] [Thermostat] Working State: idle for 0
[20/02/2024, 02:35:24] [Wyze] [Thermostat] Cool Setpoint: 75
[20/02/2024, 02:35:24] [Wyze] [Thermostat] Heat Setpoint: 69
[20/02/2024, 02:35:24] [Wyze] [Thermostat] Temp Units: 1
...
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "REDACTED",
        "username": "REDACTED",
        "port": "REDACTED",
        "pin": "REDACTED",
        "advertiser": "REDACTED"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Wyze",
            "username": "REDACTED",
            "password": "REDACTED",
            "keyId": "REDACTED",
            "apiKey": "REDACTED",
            "refreshInterval": 60000,
            "hms": true,
            "showAdvancedOptions": true,
            "apiLogEnabled": true,
            "logLevel": "debug",
            "lowBatteryPercentage": 30,
            "garageDoorAccessory": [
                "REDACTED-the-mac-in-wyze-app-specifically-for-controller-accessory"
            ],
            "excludeMacAddress": false,
            "excludedeviceType": false,
            "platform": "WyzeSmartHome"
        }
    ]
}
```

**Environment:**

* **Plugin Version**: v0.5.44
* **Homebridge Version**: 1.7.0
* **Node.js Version**: v18.19.0
* **NPM Version**: n/a
* **Operating System**: Raspbian

**Comment by jfarmer08** [comment]
For the Cam Feed this addon does not support it. 

For the Garage door you need too add the mac address of the camera in which the garage door accessory is on. 

"garageDoorAccessory" "Camera mac address"

Hope this helps.

**Comment by Zamua** [comment]
that fixed it thanks!!

do you know of any wyze plugins that do support video feeds?
