### ISSUE TITLE
Add OG Camera

### ISSUE THREAD

**Issue by sappercusps** [jfarmer08/homebridge-wyze-smart-home#240]
Hi. Any chance this is a possibility? 

[3/23/2024, 5:09:07 PM] [Wyze] Camera (Model: GW_GC1 (Mac: GW_GC1_) not supported submit a request to https://github.com/jfarmer08/homebridge-wyze-smart-home/issues to have it added

**Comment by jfarmer08** [comment]
Can you update the enums.js file with the correct model number and test? Then report back. 

![image](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/18117255/86110f74-149e-4813-a1e0-fe9d739c564a)

**Comment by carTloyal123** [comment]
What type of device is this @sappercusps ? Like doorbell, cam v4, etc?

**Comment by mitpatterson** [comment]
Not the original post, but i added it as below and it at least shows up now:

![image](https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/1526446/fbc56d17-3459-405d-9e4b-e9cdbdf49cde)

> const CameraModels = {
  WyzeCamv1Hd: "WYZEC1",
  WyzeCamV2: "WYZEC1-JZ",
  WyzeCamV3: "WYZE_CAKP2JFUS",
  WyzeCamV3Pro: "HL_CAM3P",
  WyzeCamFloodlight: "WYZE_CAKP2JFUS",
  WyzeCamPan: "WYZECP1_JEF",
  WyzeCamPanv2: "HL_PAN2",
  WyzeCamPanv3: "HL_PAN3",
  WyzeCamOutdoor: "WVOD1",
  WyzeCamOutdoor2: "HL_WCO2",
  WyzeCamOG: "GW_GC1"
}

**Comment by jfarmer08** [comment]
@mitpatterson Are you able to control it in anyway?

**Comment by mitpatterson** [comment]
> @mitpatterson Are you able to control it in anyway?

In home kit it looks like it works, but the wyze never shows the cam as "off" and shows this in the logs of the plugin:

> [4/12/2024, 9:57:20 PM] [Wyze] Wyze API Error (3005): 'unauthorized operation'
> [4/12/2024, 9:57:20 PM] Error: Wyze API Error (3005) - unauthorized operation
>     at WyzeAPI._performRequest (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/node_modules/wyze-api/src/index.js:289:13)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at WyzeAPI.request (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/node_modules/wyze-api/src/index.js:82:20)
>     at WyzeAPI.runAction (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/node_modules/wyze-api/src/index.js:493:20)
>     at WyzeAPI.cameraPrivacy (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/node_modules/wyze-api/src/index.js:1152:5)

**Comment by jfarmer08** [comment]
So for now the OG Camera cannot be added. In the feature, I will try to get one and see what i can do.
