### ISSUE TITLE
Devices take forever to update in HB or Home App.

### ISSUE THREAD

**Issue by DanielRSims** [jfarmer08/homebridge-wyze-smart-home#244]
When I open a door or give motion, the device takes 1 minute or longer to update.
**To Reproduce:**
Use device as normal and look on Homebridge accessory page until they update to current status.

**Expected behavior:**
The devices should update right away with no delay. I feel like they use to, but when I reinstalled it, there is a delay., and yes, IJ did put the Refresh Interval as low as I could.

**Environment:**

* **Plugin Version**: v0.5.46
* **Homebridge Version**: 1.8.0
* **Node.js Version**: 20.9.0
* **NPM Version**: cannot find
* **Operating System**: Windows 11 Pro

**Comment by jfarmer08** [comment]
Default there is a 60second delay.
