### ISSUE TITLE
Hello from Wyze again and there some changes coming we want to keep you posted

### ISSUE THREAD

**Issue by xcz011** [jfarmer08/homebridge-wyze-smart-home#245]
I’m an engineer at Wyze, and I wanted to inform you about some important updates to our Wyze Login API that may affect the this project. As detailed in our recent forum post ([Important Wyze App Information - 4/26/24](https://forums.wyze.com/t/important-wyze-app-information-4-26-24/297488)), we will soon be shutting down the v2 and v3 APIs. This decision was made to enhance security and prevent credential stuffing attacks.

We encourage developers to transition to our supported Developer API for login processes which this project already supports. This change will ensure continued compatibility and enhance the security of integrations.

We appreciate the effort you have put into supporting Wyze and our ecosystem through your project. If you have any questions or need further details about the Developer API and how to transition, please feel free to reach out.

Thank you for your understanding and support.

**Comment by carTloyal123** [comment]
Hey @xcz011 thank you for keeping us updated on developments at Wyze that will affect this project. I just wanted to say it is very appreciated. Transparency between Wyze and community run projects is incredibly valuable so please continue to work with us as we all develop together.

Is there anything we need to do or may I close this issue? I think the new login api is implemented in the plugin so things should be up to date with Wyze infrastructure.

Again thank you!

**Comment by xcz011** [comment]
@carTloyal123 nope. I think we guy are doing great job !! Much appriciated !!
