### ISSUE TITLE
Wyze API Errors

### ISSUE THREAD

**Issue by joshelgin** [jfarmer08/homebridge-wyze-smart-home#248]
**Describe The Bug:**
The plugin no longer logs into the Wyze API properly.

I also deleted my existing API key and created a new one, issue persists.

**To Reproduce:**
Attempt to configure the plugin.

**Expected behavior:**
Plugin should log into the Wyze API and connect my devices.

**Logs:**
'''
[04/05/2024, 15:41:35] [Wyze] Wyze API Error (2001): 'access token is error'
[04/05/2024, 15:41:35] [Wyze] Wyze API Error (2002): 'RefreshTokenError'
[04/05/2024, 15:41:35] [Wyze] Error getting devices: Error: Refresh Token could not be used to get a new access token. Error: Wyze API Error (2002) - RefreshTokenError'''

**Plugin Config:**

{
    "name": "Wyze",
    "username": "[email]",
    "password": "[password]",
    "keyId": "61e9a810-716b-4ba2-9b04-269cc82a59b5",
    "apiKey": "[apiKey]",
    "refreshInterval": 60000,
    "hms": false,
    "showAdvancedOptions": false,
    "apiLogEnabled": false,
    "pluginLoggingEnabled": false,
    "lowBatteryPercentage": 30,
    "excludeMacAddress": false,
    "excludedeviceType": false,
    "platform": "WyzeSmartHome"
}

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: v1.81
* **Node.js Version**: v18.16.0
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by joshelgin** [comment]
Maybe has to do with https://github.com/jfarmer08/homebridge-wyze-smart-home/issues/245?

**Comment by blachole** [comment]
I can confirm I am having the same problems and also generated a new API key with same error persisting.

**Comment by vascott1** [comment]
Has there been any updates on this. I was 100% working and had to reset my password. Now I am getting API errors even after creating a new API key twice. Wasn't sure I was logged in correctly the first time.

09/05/2024, 20:29:05] [wyze-smart-home] Wyze API Error (2001): 'access token is error'
[09/05/2024, 20:29:06] [wyze-smart-home] Wyze API Error (2002): 'RefreshTokenError'
[09/05/2024, 20:29:06] [wyze-smart-home] Error getting devices: Error: Refresh Token could not be used to get a new access token. Error: Wyze API Error (2002) - RefreshTokenError
[09/05/2024, 20:30:10] [wyze-smart-home] Initializing WyzeSmartHome platform...
[09/05/2024, 20:30:11] [wyze-smart-home] Wyze API Error (2001): 'access token is error'
[09/05/2024, 20:30:12] [wyze-smart-home] Wyze API Error (2002): 'RefreshTokenError'
[09/05/2024, 20:30:12] [wyze-smart-home] Error getting devices: Error: Refresh Token could not be used to get a new access token. Error: Wyze API Error (2002) - RefreshTokenError
[09/05/2024, 20:30:17] [wyze-smart-home] Request failed: AxiosError: Request failed with status code 401
[09/05/2024, 20:30:17] [wyze-smart-home] Response SetIotProp (): {
	"code": 2001,
	"current": 0,
	"hash": "1",
	"instance_id": "0d209c86c9ad436ca5210736b65f43e0",
	"isShowToast": 0,
	"message": "Access token error",
	"total": 0,
	"version": 1
}

**Comment by mpl241** [comment]
I am also having the same problem with the plugin, even after updating my API key.  The problem started sometime yesterday (2024-05-16).

```
[5/17/2024, 8:36:47 AM] [Wyze] Wyze API Error (2001): 'access token is error'
[5/17/2024, 8:36:48 AM] [Wyze] Wyze API Error (2002): 'RefreshTokenError'
[5/17/2024, 8:36:48 AM] [Wyze] Error getting devices: Error: Refresh Token could not be used to get a new access token. Error: Wyze API Error (2002) - RefreshTokenError
```

**Comment by mylylyl** [comment]
same here. maybe cause of 2FA?

**Comment by blachole** [comment]
Maybe @xcz011 can help answer this?

**Comment by Jjcord** [comment]
Wyze is pushing 2FA on all of us May 31.  Can anyone confirm status with 2FA enabled?

**Comment by HughesAndrewC** [comment]
I’ve been using 2FA with Microsoft Authenticator for months without issue.

**Comment by anderfrank** [comment]
I've had 2FA enabled on my Wyze account for a long time and had no issues until this recent Wyze API change.

**Comment by Ogerbrow** [comment]
Same here, I have had 2FA in place for a long time. Any progress here?

**Comment by anderfrank** [comment]
> Same here, I have had 2FA in place for a long time. Any progress here?

I know the Wyze integration in HACS for Home Assistant is working fine so I have switched to that for the time being.

**Comment by jfarmer08** [comment]
This addon does not use 2FA anymore. It was remove a few revision back. Can
you confirm that your using and api key. Also when you’re changing over you
might have to delete your refresh token from the persist directory.

Thanks Allen :)

**Comment by anderfrank** [comment]
Can you confirm the new API (https://github.com/jfarmer08/homebridge-wyze-smart-home/issues/245) is implemented with this plugin?

I have been using an API key with this plugin for many months and it just stopped working recently with Wyze disabling the old API.

**Comment by name99-org** [comment]
I'm seeing the same behavior. Everything just stopped working. Communication between HomeKit and Wyze plugin is fine (tap a light on in Home.app, the light is displayed in the UI as going on with no error, and on the Homebridge web page the light is also displayed as on - but in reality it's unchanged, still off. 

Wyze logs show NO errors...
Seems like the plugin is sending requests off into the ether, getting no response (or a canned OK response) but Wyze central is not honoring the requests, and plugin is not even aware that requests are not being honored.

My guess is the #245 issue is driving all this. 

BTW, before the 2FA deadline I asked Wyze tech support if this would impact Homebridge and was told no. So, yeah, another triumph for tech support...

**Comment by yodaluca23** [comment]
This may be redundant information, as several have already answered, but I thought I might as well.

I have been using 2FA since I made my Wyze account, but I am getting these errors too, I tried a new API key/ID, and the problem persists, as others have noted this is likely to do with Wyze API changes, I hope this can be resolved, I will happily provide any logs, or other information if it may help resolve this issue.

**Comment by NateBlanchard** [comment]
Sorry to pile on here, but I'm having the same issue. I've been using an API key and already had 2FA enabled before the switch, but around that same time the plugin completely stopped working. I'm getting the same API errors others have mentioned, but haven't had any problems with Scrypted. I tried regenerating the key, but no difference. 

Has anyone else had any luck in troubleshooting? I'm happy to wait patiently and appreciate the work I'm sure it'll take to fix, but I'm hoping I'm just doing something wrong.

**Comment by joshelgin** [comment]
I can confirm that the suggestion "delete your refresh token from the persist directory" solved the issue.
