### ISSUE TITLE
Add variable to ignore selected devices

### ISSUE THREAD

**Issue by cheme75** [jfarmer08/homebridge-wyze-smart-home#31]
Add ability to whitelist desired devices or blacklist to ignore selected devices. I’d like to ignore all my cam on/off toggles since I never use them. I also have a spare plug that I’m not currently using that would be nice to ignore. Optionally, I have only a few active devices so in my case it would be easier to just whitelist the devices I want to use in homebridge. If ability exists, I’m not finding it.

**Comment by jfarmer08** [comment]
I will see what I can do. Cloud use some help to define the requirements.

**Comment by Ammarjeddin** [comment]
Adding a device ID filter in the plug-in setup menu:
When a user uses the ID Filter:
- Devices with the ID specified will not be imported into homebridge and ignored.
- Device ID might be S/N or device Name set on Wyze app.

**Comment by jfarmer08** [comment]
So is the camera the Main device everyone wants to ignore?

**Comment by cheme75** [comment]
> 
I suspect most would be mostly interested in the wired cams: v1, v2, v3. I, personally, would like to also ignore the doorbell db3. My orig doorbell is a “wyzedb3” - not sure name of the newer db. I don’t have an outdoor cam, might be handy to toggle on/off for those who may need to conserve battery life. But for me I have 1 db3 doorbell cam, 2 v2 cams, and 2 db3 doorbell cams from beta testing I use with the Wyze bridge and scrypted for hksv (fwiw, you can power them from a micro USB port on the backside so can be useful for monitoring). I never toggle my cams off. The only ones I know regularly toggling to restart cams are those using the rtsp fw and have periodic problems. Hopefully others will chime in.

**Comment by Ammarjeddin** [comment]
If we are using a MAC address or device ID then let's have the option to ignore any device. Why only cams. 

In my situation, I want to ignore a lock that is installed out side of my house. 

So I don't want it to be displayed on my Home App.

**Comment by Ammarjeddin** [comment]
I guess when pulling from the API we get a list of Devices from the Wyze Account linked. 
So when a filter ID is used, we can ignore that Device and remove it from the query? 

I don't know if it's that easy.

I know there's another plug-in that have this implemented I can share it later on

**Comment by jfarmer08** [comment]
I have update NPM with a beta version. If you would like to test this that would be great. Currently it will support filter by device type only. I will add more to this as time allows.

**Comment by jfarmer08** [comment]
Well I just found an issue. If you already have the device in home bridge it will error while trying to remove it.

**Comment by Ammarjeddin** [comment]
I think we need to clear the cache from the homebridge setting. That should solve it ?

**Comment by jfarmer08** [comment]
I think that seems reasonable, but I will have to look into it.

**Comment by Ammarjeddin** [comment]
https://github.com/milo526/homebridge-tuya-web

This plugin has the hide accessory feature and it's working 

Maybe will help !

**Comment by jfarmer08** [comment]
That might help. Thank You.

**Comment by kingb2019** [comment]
The homebridge-ring v11.3.0 plugin has this option as well. It allows you to view the JSON config as well if that helps. I've looked at various ways to perform this and the hard part is the granularity for me. You may not want to ignore the camera but may want to ignore the "switch" associated with the camera. You may want to trigger from the switch but not see the feed, etc.. It'll take some work for sure.

**Comment by cheme75** [comment]
> The homebridge-ring v11.3.0 plugin has this option as well. It allows you to view the JSON config as well if that helps. I've looked at various ways to perform this and the hard part is the granularity for me. You may not want to ignore the camera but may want to ignore the "switch" associated with the camera. You may want to trigger from the switch but not see the feed, etc.. It'll take some work for sure.

For me, I use docker wyze bridge and scrypted for the cameras - I can ignore everything about the cams in the wyze smart home plugin since I don't need them in homebridge at all. I can see others may have some use for the switch. although there are other plugins for the cams in homebridge but I don't use them so not sure what options they offer for integrating the cam switch. So, not sure what granularity you mean when this particular plugin can just have a variable to ignore the entire cam since that's the only aspect of the cam that it detects.

**Comment by kingb2019** [comment]
> > The homebridge-ring v11.3.0 plugin has this option as well. It allows you to view the JSON config as well if that helps. I've looked at various ways to perform this and the hard part is the granularity for me. You may not want to ignore the camera but may want to ignore the "switch" associated with the camera. You may want to trigger from the switch but not see the feed, etc.. It'll take some work for sure.
> 
> For me, I use docker wyze bridge and scrypted for the cameras - I can ignore everything about the cams in the wyze smart home plugin since I don't need them in homebridge at all. I can see others may have some use for the switch. although there are other plugins for the cams in homebridge but I don't use them so not sure what options they offer for integrating the cam switch. So, not sure what granularity you mean when this particular plugin can just have a variable to ignore the entire cam since that's the only aspect of the cam that it detects.

Granularity meaning that not everyone is just going to want the option you are describing. Therefore, the programmer/dev must think big picture, so they don't have to rework/rebuild the programming structure when the requests are made. There's a lot of devices and a lot of options. Not everyone uses bridge/scrypted so they will want to be able to enable/disable these filters within this one singular plugin. When I am writing out a project as this, you must engineer it with all variables in mind.

**Comment by cheme75** [comment]
> 

ok I get it...

**Comment by charleychen88** [comment]
I would add another use case which Wyze doesn't handle well either.  I have wyze devices in 2 homes running separate homebridge.  I would like to be able to filter specific devices for each home.  If there's a way to config inclusion/exclusion by device id, that would be the most flexible.

**Comment by ccwarez88** [comment]
Not sure if I would add to this thread or create a bug. 

**Background:**
I installed the beta v0.5.24-beta.  It runs fine with no devices excluded.  However, once I exclude an device type, it's generating an error.  I've tried different combination of devices types that I excluded, included types that I have, a mix and only types that I do not have.  It generates the same error.  

**Here are the logs.**
[27/10/2022, 09:16:18] [Wyze] Launched child bridge with PID 4925
[10/27/2022, 9:16:20 AM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[27/10/2022, 09:16:20] [Wyze] Loaded homebridge-wyze-smart-home v0.5.24-beta.0 child bridge successfully
[10/27/2022, 9:16:21 AM] Loaded 24 cached accessories from cachedAccessories.0ED6384D51C5.
Error: Cannot find the bridged Accessory to remove.
    at Bridge.Accessory.removeBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:640:13)
    at Bridge.Accessory.removeBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:654:12)
    at BridgeService.handleUnregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:404:17)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.unregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:355:10)
    at WyzeSmartHome.configureAccessory (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:184:16)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:186:24)
[27/10/2022, 09:16:23] [Wyze] Child bridge process ended
[27/10/2022, 09:16:23] [Wyze] Process Ended. Code: 1, Signal: null

**Comment by kliu99** [comment]
I can help take a look at it this weekend if no one beats me first.

**Comment by jfarmer08** [comment]
Beta Version [0.5.24-beta.1](https://www.npmjs.com/package/homebridge-wyze-smart-home/v/0.5.24-beta.1) has been published. Please let me know if this work for you.

**Comment by kliu99** [comment]
Tried both filter by MAC and by type. Works for me. Thanks for working on it. :)

**Comment by cheme75** [comment]
Will try to load as soon as I have some free time. Not too Linux fluent so may need to get some command line help.
