### ISSUE TITLE
Light switch support

### ISSUE THREAD

**Issue by boothmusic** [jfarmer08/homebridge-wyze-smart-home#34]
It’d be great if you were able to add support for the light switch. It’s such a great product but utilizing IFTT is super slow and usually unresponsive, because you can program each press to be a specific command to the WYZE app, it’d be great to utilize apples automations to control specific lights in your house while maintaining constant power to the smart bulbs.

**Comment by tek9r** [comment]
Looking for this aswell

**Comment by lp86** [comment]
Looking for this too, added a new switch and spent way too much time troubleshooting just to check that it's not on the supported list :)

**Comment by jfarmer08** [comment]
It is on my plan

**Comment by boothmusic** [comment]
![Uploading D81F93A3-5D70-4E68-A837-A1B8EFBD37E6.gif…]()

**Comment by boothmusic** [comment]
Wondering if there was an update on this? More out of curiosity than impatience

**Comment by jfarmer08** [comment]
I have been working on this and will be posting a release within the next few weeks. I do have switch support on my test system at this time.

**Comment by boothmusic** [comment]
This is very exciting. Does it work well with the automations inside apples HomeKit?

**Comment by jfarmer08** [comment]
I will be posting a beta within the next week or so, but have not test automation with them.

**Comment by jfarmer08** [comment]
I have not created a beta yet, but I will

**Comment by jfarmer08** [comment]
@boothmusic Do you have a test system, if not I would recommend one.

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.25-beta.1

I would recommend using a test system.

**Comment by jfarmer08** [comment]
@boothmusic new beta release. Hopefully this one goes a little better. 

Currently only Single Press is supported.

**Comment by boothmusic** [comment]
@jfarmer08 looks like the problem still persists. if its helpful to know, if you change the status from the wyze app (i.e. turning the switch OR their outlets on/off; that change in status does not report over to home bridge)

**Comment by boothmusic** [comment]
@jfarmer08 upon further testing. if I power the smart outlet off physically, it takes about 45 seconds for home bridge to recognize its status. 

if I power the switch on or off physically home bridge does not recognize it

**Comment by jfarmer08** [comment]
<img width="535" alt="Screen Shot 2022-12-07 at 6 21 11 PM" src="https://user-images.githubusercontent.com/18117255/206325795-1afa76f0-4b11-4a60-9126-98edf6806123.png">

Which one do you have checked? How many Switch?

**Comment by jfarmer08** [comment]
What is your refresh interval set at? I can control the switches fine, but the status is delayed. I think I have a solution for that. You might want to turn on debug and make sure you're not seeing any errors in the background.

**Comment by boothmusic** [comment]
I've got mine set to smart control because I want it to control automation of smart bulbs in the house. when I try and change the interval on the application its set to 1x a minute. I can't have it go any lower than that.

**Comment by boothmusic** [comment]
60000ms is the interval setting right now

**Comment by boothmusic** [comment]
sounds good, thank you!

**Comment by tbsaunders1** [comment]
i loaded the beta.2 file just now, and my switches are working as expected in HomeKit! no impacts to two of my other wyze items (two plugs on lights that i can see right now) - i'll confirm the rest of my wyze accessories are functioning as expected in the next couple of days. thanks so much for pushing this out - SUPER helpful - this brand of device is relatively affordable and having the ability to control their in-wall switches in HomeKit is huge. i have several still in the box that i have been anticipating this plugin's switch update for some time now - glad it's up and running!!! great work!!! 

if i can do anything to help you with data or setup config items i'll do what i can to help. i probably have a dozen or more wyze accessories in my setup at present.

**Comment by jfarmer08** [comment]
After a week of testing how does it look? I have one more beta to put out in the next few days and I would like to fix any thing that I can with the switches. So for my testing it's working ok. 

My setup I am running docker with the latest version of homebridge and beta 2 of wyze. I have 3 switch's setup as classic control.  I did change them over to IOT control and didn't see any thing major. I am not currently running 2fa at this time. For my other accessories I have 3 locks, 15 lights, 2 outdoor plugs and 6 plugs.  Everything seems to be working fine. 

For the next release I have focused on the amount of calls to wyze. I really don't want to be in a situation where we have to shut this down. As your have notice the default time for refresh was moved to 60 seconds. I am starting to store the device last known state in the config file and when one device ask for a update I will be able to store the value for all devices. And so when another device wants a update I can reference the config and determine if I can use that value or request a new one. It will take some time to get this right, but the over performance will be better.

**Comment by mammerman** [comment]
I've been testing the beta 3 today with a light switch and it's working great.  So far no issues.  I have it in an automation in Home with a motion sensor and it works almost instantaneously.  

Other accessories include 10 smart plugs and 2 outdoor smart plugs.

**Comment by jfarmer08** [comment]
@mammerman Thank you for the update. There will be a new beta release soon to address a couple of things with the switch, but also adding more support for other items. A lot of the code has changed and so it will be hard.

**Comment by jfarmer08** [comment]
@mammerman what type of sensors are you using?

**Comment by Glennkh** [comment]
I tested v0.5.2-5.beta.3 today. I have a wyze motion sensor v2 and a wyze switch (classic control) added to homebridge and I am able to control the switch without any issues from homekit. I tried setting up some automation with homekit.

When wyze motion sensor v2 detects motion -> turn wyze switch on

This was inconsistent for me sometime it worked some times it didn't. When it did work it took about 20 - 30 seconds for the light switch to turn on after motion was detected.

**Comment by jfarmer08** [comment]
This I can understand. The polling limit is 60 seconds.

**Comment by anderfrank** [comment]
Just wanted to say thank you to everyone who helped get this working. Just installed the latest beta and it works great for my two switches!

**Comment by jfarmer08** [comment]
https://www.npmjs.com/package/homebridge-wyze-smart-home/v/0.5.25-dev.0

So things go mixed up, and so I am releasing a dev version for the wall switch. After its in dev awhile I will move it back to Beta and from there to production. 

A lot of changes in this release so beware.

**Comment by jfarmer08** [comment]
Please open a new ticket for any issues found.
