### ISSUE TITLE
Reduce cached accessory logspam

### ISSUE THREAD

**Issue by traviswparker** [jfarmer08/homebridge-wyze-smart-home#46]
Line 122 of WyzeSmartHome.js is logging all accessories at every refresh interval. 

The logging could be moved to 
```
this.log.info(`Loading accessory from cache ${homeKitAccessory.context.nickname} (MAC: ${homeKitAccessory.context.mac})`)
```

in configureAccessory at line 184 of WyzeSmartHome.js. This would log cached accessories once at plug-in startup.

**Comment by jfarmer08** [comment]
I will include this in the next major release with a lot of other changes.

**Comment by brsexton** [comment]
Hello. I recently updated the Wyze plugin and am getting: [Wyze] Loading accessory from cache... every few seconds. Is there any way to reduce these logs or disable them? When I revert back to the old version plugin, these logs stop.

**Comment by jfarmer08** [comment]
As stated above this will be addressed in the next release

**Comment by brsexton** [comment]
> As stated above this will be addressed in the next release

I'm sorry. I somehow missed that response. Thank you for working on this.

**Comment by carTloyal123** [comment]
Can we close this?

**Comment by jfarmer08** [comment]
This is currently in the dev branch. After we have thermostat support I will create a new beta release. I was going to push this a few weeks ago but didn't have time.

**Comment by tuanchris** [comment]
any progress on this?

**Comment by jfarmer08** [comment]
Updated Master to version 5.25.1
