### ISSUE TITLE
Support for DoorBell

### ISSUE THREAD

**Issue by yodaluca23** [jfarmer08/homebridge-wyze-smart-home#47]
**Is your feature request related to a problem? Please describe:**
I would like to view my Wyze doorbell Pro with HomeKit.

**Describe the solution you'd like:**
Add support with this plugin for both the Wyze Video DoorBell/Pro.

**Comment by jfarmer08** [comment]
Currently not planning on having support for cameras.

**Comment by jfarmer08** [comment]
I don't have the time to understand what will need to be done for camera's. Also I am working on support for switch's and thermostat.
