### ISSUE TITLE
Illegal Value

### ISSUE THREAD

**Issue by Ogerbrow** [jfarmer08/homebridge-wyze-smart-home#7]
I am getting this constant error that I think is from my color bulbs. 

This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 638 exceeded maximum of 500. See https://homebridge.io/w/JtMGR for more info.

**Comment by jfarmer08** [comment]
What type of bulbs are you using and what color are you setting in the app?  Also if you turn on debug it might help.

**Comment by Ogerbrow** [comment]
I am using the Wyze color bulbs. I don’t think the color is the issue as I get the warning constantly. I will turn on debug.

Sent from my iPhone

On Jun 20, 2022, at 7:05 PM, jfarmer08 ***@***.***> wrote:

﻿

What type of bulbs are you using and what color are you setting in the app? Also if you turn on debug it might help.

**Comment by jfarmer08** [comment]
Updated Color Temp Value. I  hope this will correct the issue.
