### ISSUE TITLE
Lock Status Reversed

### ISSUE THREAD

**Issue by jeffreykmc247** [jfarmer08/homebridge-wyze-smart-home#71]
**Describe The Bug:**
I currently have the fingerprint sensor lock which is picked up properly in Homebridge, but the lock status is reversed.  That is, it is reporting the lock is open, when it in fact is not, and vice versa.

Also seeing this in the logs if it applies - This plugin generated a warning from the characteristic 'Current Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

 "name": "Wyze",
            "username": "XXXX",
            "password": "XXXX",
            "refreshInterval": 60000,
            "platform": "WyzeSmartHome"

**Screenshots:**

**Environment:**

* **Plugin Version**:0.5.24
* **Homebridge Version**: v1.6
* **Node.js Version**: v16.16
* **NPM Version**: 
* **Operating System**: Raspian

**Comment by jfarmer08** [comment]
Can upload the logs for this? I need to know the model number. In the code I will change the state based on that.
