### ISSUE TITLE
Wall switches

### ISSUE THREAD

**Issue by kizzi81** [jfarmer08/homebridge-wyze-smart-home#76]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by kizzi81** [comment]
Oh geez.  I just put in the text box that I would love to see my Wyze wall switches on my apple homekit through hoobs.  Sorry, if this hasn't even been started yet.  I didn't see anything when I read through the versions.  Thanks!!!

**Comment by jfarmer08** [comment]
Check out the beta branch.
