### ISSUE TITLE
Cameras are coming through as Plugs, not Cameras

### ISSUE THREAD

**Issue by voosman12** [jfarmer08/homebridge-wyze-smart-home#78]
**Describe Your Problem:**
Wyze cameras are displaying as Plugs, not cameras in accessories. 

**Logs:**

[1/31/2023, 10:16:18 AM] [Wyze] Loading accessory from cache Living Room Cam (MAC:)
[1/31/2023, 10:16:18 AM] [Wyze] Loading accessory from cache Bedroom Cam (MAC:)
[1/31/2023, 10:16:18 AM] [Wyze] Loading accessory from cache xxxxxxx’s Room (MAC:)

**Plugin Config:**

{
    "bridge": {
        "name": "Homebridge 2D7D",
        "username": "0E:1D:A9:23:2D:7D",
        "port": 51217,
        "pin": "",
        "advertiser": "bonjour-hap"

            "name": "Wyze",
            "username": "xxxxxx@aol.com",
            "password": "",
            "refreshInterval": 60000,
            "entryExitDelay": 30,
            "mfaCode": "xxxxxx",
            "showAdvancedOptions": false,
            "excludeMacAddress": false,
            "excludedeviceType": false,
            "platform": "WyzeSmartHome"

**Screenshots:**

**Environment:**

* **Plugin Version**:  v0.5.24.1
* **Homebridge Version**: [homebridge-config-ui-x v4.50.2](https://github.com/oznu/homebridge-config-ui-x)
* **Node.js Version**: [16.16.0](https://homebridge.io/w/JTKEF)
* **NPM Version**: 
* **Operating System**: MacOS

**Comment by rmohns** [comment]
Similar problem, except mine are appearing as _Switches_, not Cameras. Same plug-in, homebridge and node versions. 
NPM version 8.11.0

**Comment by jfarmer08** [comment]
They should show as switch's since the only thing that is implemented is turning the camera on or off.

**Comment by rmohns** [comment]
Thanks, @jfarmer08! Did not realize that. Thank you for the quick reply.
