### ISSUE TITLE
Contributing to reverse engineering camera webview?

### ISSUE THREAD

**Issue by rnwolfe** [jfarmer08/homebridge-wyze-smart-home#80]
Hi @ jfarmer08 - I'd like to contribute to getting the camera functionality to extend beyond the switch on/off capability and enable viewing of the stream. I'm not sure if it is going to work, but I have been looking at the new [Wyze Webview](https://view.wyze.com/) as a starting point. 

Admittedly, I am a bit new to homebridge, but wonder if you have some tips/guidance that you would suggest or at least want someone contributing to follow. In lieu of a CONTRIBUTING file, I figured I would ask. 

Cheers!

**Comment by jfarmer08** [comment]
I can try to write something up for you, but it will take a little bit of time.
