### ISSUE TITLE
Adaptive Lighting support

### ISSUE THREAD

**Issue by ghelytap** [jfarmer08/homebridge-wyze-smart-home#81]
It'd be great if bulbs (Wyze color bulbs in my case) supported Homekit's Adaptive Lighting feature that adjusts color temperature throughout the day. From what I've read there are other homebridge plugins that enable this for other bulb brands.

**Comment by ghelytap** [comment]
Apologies for the formatting, I'm new to GitHub.

**Comment by jfarmer08** [comment]
I will see what I can do.

**Comment by DiscoveryOV** [comment]
I think this would be a great feature to make use of if possible.

**Comment by carTloyal123** [comment]
Added to feature backlog here: #224
