### ISSUE TITLE
Robot Vacuum Support

### ISSUE THREAD

**Issue by ghelytap** [jfarmer08/homebridge-wyze-smart-home#82]
I'd love basic vacuum support. A switch for vacuum or return to charge would be sufficient, individual rooms would be nice but not a big deal for me. I've troubleshot other plugins for hours with no success, so it would be great to have it included in this one that's always worked well.

**Comment by jfarmer08** [comment]
I can only add hardware that I own. With that said I will see what I can do.

**Comment by RMCob** [comment]
See homebridge-wyze-robovac

**Comment by carTloyal123** [comment]
See @RMCob repo for a homebridge plugin or donate a vacuum to @jfarmer08 otherwise closed for now due to lack of hardware for this item. Thanks @ghelytap and there is a ticket at [wyze-api vacuum support](https://github.com/jfarmer08/wyze-api/issues/4) you can keep track of as well if needed.
