### ISSUE TITLE
Wyze Cam Pan v3 is not recognized properly 

### ISSUE THREAD

**Issue by traviswparker** [jfarmer08/homebridge-wyze-smart-home#84]
**Describe The Bug:**
The Wyze Cam Pan v3 is not properly recognized and generates the following error in the HB logs:
`[homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.`

The switch accessory is always off after refresh. Turning the camera off and on works, but the switch does not reflect the current state.

**To Reproduce:**
Have a Pan v3 on the Wyze account.

**Expected behavior:**
Pan v3 should be properly recognized as a camera and the power_switch device param handled

src/accessories/WyzeAccessory.js line 149 should be:
`        if(productModel == "WYZEC1-JZ" || productModel == "HL_PAN3" || productModel == "WYZEDB3" || productModel == "WYZE_CAKP2JFUS") {
`
There are probably other product_model strings that need to be included here (v2 Pan, Outdoor, etc..) but I do not know what they are.

**Environment:**
* **Plugin Version**: 0.5.25.1
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 18.13.0
* **Operating System**: Docker

**Comment by traviswparker** [comment]
Alternative you could remove the model check or only exclude unsupported models, and simply go by device type for cameras. That is what I ended up doing in my local copy.

**Comment by jfarmer08** [comment]
Would you like to create a pull request if you think it will help others?

**Comment by traviswparker** [comment]
Sure, but I'll have to do it later from desktop. This seems to still be there in npm version 0.5.26. I don't have a full list of supported camera product IDs, but it works for me if I simply remove the product ID check under case "Camera":

**Comment by anderfrank** [comment]
Seems like this same error affects the Pan Cam v1 as well. Not sure what changed because this plugin used to work fine with those cams.

**Comment by anderfrank** [comment]
Update: Adding          || productModel == "WYZECP1_JEF"         to my local "WyzeAccessory.js" file and rebooting HB resolved the error and mow my Pan Cam v1s show up properly in HB.


Here are all of the cams and their model #s (taken from the Wyze-Docker-Bridge github page)

Wyze Cam v1 [HD only] | WYZEC1 | 
Wyze Cam V2 | WYZEC1-JZ | 
Wyze Cam V3 | WYZE_CAKP2JFUS | 
Wyze Cam V3 Pro [2K] | HL_CAM3P | 
Wyze Cam Floodlight | WYZE_CAKP2JFUS | 
Wyze Cam Pan | WYZECP1_JEF | 
Wyze Cam Pan v2 | HL_PAN2 | 
Wyze Cam Pan v3 | HL_PAN3 | 
Wyze Cam Pan Pro [2K] | HL_PANP | 
Wyze Cam Outdoor | WVOD1 | 
Wyze Cam Outdoor v2 | HL_WCO2 | 
Wyze Cam Doorbell | WYZEDB3 | 
Wyze Battery Cam Pro | AN_RSCW | 
Wyze Cam Doorbell Pro 2 | AN_RDB1 | 
Wyze Cam Flood Light Pro [2K] | LD_CFP | 
Wyze Cam Doorbell Pro | GW_BE1 | 
Wyze Cam OG | GW_GC1 | 
Wyze Cam OG Telephoto 3x | GW_GC2
