### ISSUE TITLE
Just updated to v0.5.25.1 and it is crashing homebridge

### ISSUE THREAD

**Issue by vascott1** [jfarmer08/homebridge-wyze-smart-home#85]
**Describe Your Problem:**
I just updated the the most recent version of the plugin since I saw it supported wall switches now. Once I installed i did not see the wall switches so decided to restart Homebridge. It would start and crash. Then proceeded to loop through starting/crashing.

I thought I would revert to the previous version but the link to do that no longer shows. Screenshot attached. I have no upgraded to v1.6.0 because my install has been stable. Do I need that version to use the latest plugin?

Prior to upgrading I was using version 5.24

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
[07/03/2023, 22:53:42] TypeError: Cannot read properties of undefined (reading 'device_id')
    at WyzeHMS.getHmsID (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:598:92)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at WyzeHMS.updateCharacteristics (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:27:9)
    at WyzeHMS.update (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:351:7)

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
Config.json attached
```

**Screenshots:**

**Environment:**

* v0.5.25.1:
* *1.5.0: 
* *v16.15.0: 
* 8.5.5*: 
* *Raspbian GNU/Linux Buster (10): 

[config-3.json.txt](https://github.com/jfarmer08/homebridge-wyze-smart-home/files/10917127/config-3.json.txt)
![Screen Shot 2023-03-07 at 11 18 00 PM](https://user-images.githubusercontent.com/47582187/223618480-451469f1-320f-4eaa-8f58-7570ca6002a8.png)

**Comment by palettecollective** [comment]
yeah, after updating i'm also getting "[homebridge-wyze-smart-home] Failed to check registry.npmjs.org for updates: "Invalid Version: 0.5.25.1" - see https://homebridge.io/w/JJSz6 for help." without the option to revert to older versions in my settings as well.

**Comment by vascott1** [comment]
That worked perfectly. Was able ot go back to 5.24  Just have to figure out why the latest doesn’t work.

Thanks Travis.

**Comment by traviswparker** [comment]
You have Home Monitoring don’t you? There is a comment in the code about needing to fetch the HMS ID from the device list, not the plan list. Seems Wyze changed the API and the plug-in isn’t handling it gracefully. If you don’t have HMS you won’t see this bug.On Mar 11, 2023, at 10:39, vascott1 ***@***.***> wrote:﻿
That worked perfectly. Was able ot go back to 5.24  Just have to figure out why the latest doesn’t work.

Thanks Travis.

**Comment by vascott1** [comment]
I do have the hub set up for water leak monitoring so yes. So, for now water leaks or wall switches. Lol.    Hopefully there will be an update. Thanks for the info and the advice to fix the the previous issue.
  

  
Scott
  
  
  
  
  
  
  

  
  
>

**Comment by jfarmer08** [comment]
I will try and get a fix for this soon as I can.

**Comment by jscherry** [comment]
Sorry to ask but I'm not sure where to edit the package.json? I'm running homebridge on macos and using the homebridge ui. Where or how do I Changing it to 0.5.2-5.1 in package.json will fix update checks and allow you to select alternate versions. Any help greatly appreciated. Thanks

**Comment by vascott1** [comment]
The latest version 0.5.26 resolved the issue. I am still waiting for my wall switches to show up. I see the plugin loading my accessories from cache in the log. I do not see them in the "exclude" list as a type so will give it some time.

I did need to update to Homebridge 1.6.0 to remove this error:

25/03/2023, 10:13:47] TypeError: Cannot read properties of undefined (reading 'device_id')
    at WyzeHMS.getHmsID (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:598:92)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at WyzeHMS.updateCharacteristics (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:27:9)
    at WyzeHMS.update (/usr/local/lib/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:351:7)
[25/03/2023, 10:13:47] Got SIGTERM, shutting down Homebridge...

**Comment by vascott1** [comment]
I am back to 5.24. Things ran stable for a 24-48 hours? I forget. Then homebridge went offline and kept flapping. The error was about HMS. I will grab the logs. Seems odd to mention but it seems there is always a trigger effect and when this plugin has an issue I have an issue with homedbrdige-ring as well and need to regen my access token.  All in all
I am ok on 5.24 for. Or since even on 5.26 I could not get it to show my wall switches. I posted a question about that and deleting my accessories cache? Some plugins have a confit option to do that on next restart. Not so here. I can add logs to this message if that might help. Still, this plugin does 99% of what o want to no complaints !

**Comment by jfarmer08** [comment]
@vascott1 are you still having issues with your wall switch not showing? If so can you post or send me the logs?

**Comment by vascott1** [comment]
I am not sure as I just posted #112 with the newest version. I cannot get past a NODE_MODUIE_VERSION error. It crashes homebridge.
  

  
Thanks for checking. The only thing I need is the wall switches. Everything else works great.
  

  
Scott
  

  
  
  
>
