### ISSUE TITLE
Warning for characteristic 'On'

### ISSUE THREAD

**Issue by anderfrank** [jfarmer08/homebridge-wyze-smart-home#87]
**Describe The Bug:**
Error recieved every minute after installing 0.5.2.x plugin

**To Reproduce:**
Install plugin, reboot homebridge

**Expected behavior:**
Did not recieve error in version 0.5.24, so do not expect error. Might be related to new code for switches?

**Logs:**
[homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.

version 0.5.24 also posts a message to the log every minute regarding loading cached devices. 

Both plugin versions seem to slow my Homebridge instance down and cause HomeKit to be slow to respond/display device statuses for all Homebridge plugins, not just Wyze. Switching to back version 0.5.18 resolves performance issues.

**Plugin Config:**
            "name": "Wyze",
            "username": "<redacted>@gmail.com",
            "password": "<redacted>",
            "refreshInterval": 60000,
            "entryExitDelay": 30,
            "mfaCode": "<redacted>",
            "showAdvancedOptions": false,
            "excludeMacAddress": false,
            "excludedeviceType": false,
            "platform": "WyzeSmartHome",
            "_bridge": {
                "username": "0E:69:5A:D2:DD:33",
                "port": 31224

**Environment:**

* **Plugin Version**: 0.5.2-5.1
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 16.18.0
* **NPM Version**: 
* **Operating System**: Docker

**Comment by holocronology** [comment]
Also seeing this.

**Comment by jfarmer08** [comment]
Can you turn on debug and collect the logs.

**Comment by holocronology** [comment]
Also seeing this:

`
[3/28/2023, 8:44:23 AM] [Homebridge UI] [homebridge-wyze-smart-home] Failed to check registry.npmjs.org for updates: "Invalid Version: 0.5.25.1" - see https://homebridge.io/w/JJSz6 for help.
[3/28/2023, 8:44:23 AM] [Homebridge UI] [homebridge-wyze-smart-home] Failed to check registry.npmjs.org for updates: "Invalid Version: 0.5.25.1" - see https://homebridge.io/w/JJSz6 for help.
`

**Comment by anderfrank** [comment]
> 

at this path (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/) there is a file named package.json. Open this and change the "version" from 0.5.25.1 to 0.5.2-5.1. Save and restart Homebridge.

**Comment by Z1mDMan** [comment]
I can confirm when I remove switches from the allowed devices, the error doesn't show

**Comment by anderfrank** [comment]
Update: Adding || productModel == "WYZECP1_JEF" to my local "WyzeAccessory.js" file and rebooting HB resolved the error and now my Pan Cam v1s show up properly in HB.

Here are all of the cams and their model #s (taken from the Wyze-Docker-Bridge github page)

Wyze Cam v1 [HD only] | WYZEC1 |
Wyze Cam V2 | WYZEC1-JZ |
Wyze Cam V3 | WYZE_CAKP2JFUS |
Wyze Cam V3 Pro [2K] | HL_CAM3P |
Wyze Cam Floodlight | WYZE_CAKP2JFUS |
Wyze Cam Pan | WYZECP1_JEF |
Wyze Cam Pan v2 | HL_PAN2 |
Wyze Cam Pan v3 | HL_PAN3 |
Wyze Cam Pan Pro [2K] | HL_PANP |
Wyze Cam Outdoor | WVOD1 |
Wyze Cam Outdoor v2 | HL_WCO2 |
Wyze Cam Doorbell | WYZEDB3 |
Wyze Battery Cam Pro | AN_RSCW |
Wyze Cam Doorbell Pro 2 | AN_RDB1 |
Wyze Cam Flood Light Pro [2K] | LD_CFP |
Wyze Cam Doorbell Pro | GW_BE1 |
Wyze Cam OG | GW_GC1 |
Wyze Cam OG Telephoto 3x | GW_GC2
